import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async({page})=>{
  await page.goto('/tieu-hoc')
  await page.evaluate(async()=>{localStorage.clear();const databases=await indexedDB.databases();await Promise.all(databases.map(database=>new Promise(resolve=>{const request=indexedDB.deleteDatabase(database.name);request.onsuccess=request.onerror=request.onblocked=()=>resolve()})))})
  await page.reload()
})

test('vườn lớp 2 xử lý thiếu thông tin, sửa nhãn và lưu so sánh',async({page})=>{
  const eagerAudioRequests=[]
  page.on('request',request=>{if(request.resourceType()==='media')eagerAudioRequests.push(request.url())})
  await page.getByRole('tab',{name:/Lớp 2/}).click()
  await page.locator('#game-2-data-garden').click()
  await expect(page.locator('.garden-criterion')).toContainText('bộ phận của cây có hạt ở bên trong')
  await expect(page.locator('#garden-run')).toBeDisabled()
  await page.locator('#garden-predict-unknown').click()
  await page.locator('#garden-reveal').click()
  await page.locator('#garden-label-other').click()
  await page.locator('#garden-run').click()
  await expect(page.locator('.garden-runs article')).toHaveCount(1)
  await expect(page.locator('.garden-runs')).toContainText('Dự đoán chưa khớp')
  await page.locator('#close-game').click()
  await page.locator('#game-2-data-garden').click()
  await expect(page.locator('.garden-runs article')).toHaveCount(1)
  await page.locator('#garden-radish-other').click()
  await page.locator('#garden-run').click()
  await expect(page.locator('.garden-runs article')).toHaveCount(2)
  await expect(page.locator('.garden-runs')).toContainText('Dự đoán khớp')
  await page.locator('#garden-reason-label').click()
  await page.locator('#finish-garden-lab').click()
  await expect(page.getByText('HOÀN THÀNH VƯỜN DỮ LIỆU')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await expect(page.locator('#teacher-audio-title')).toHaveText('Preset MP3 đang phát hành')
  await expect(page.locator('.teacher-audio-catalog')).toContainText('Tiểu học: Trúc Ly')
  await expect(page.locator('.teacher-audio-catalog')).toContainText('THCS: Ngọc Huyền')
  await expect(page.locator('.teacher-audio-catalog')).toContainText('THPT: Minh Đức')
  await expect(page.locator('.vieneu-voices summary')).toHaveText('Catalog VieNeu: 20 giọng (19 tiếng Việt)')
  await page.locator('.vieneu-voices summary').click()
  await expect(page.locator('.vieneu-voices > div > span')).toHaveCount(20)
  await expect(page.locator('.vieneu-voices')).toContainText('Phạm Tuyên')
  await expect(page.locator('.vieneu-voices')).toContainText('Ngọc Trân')
  await page.locator('#teacher-activity-select').selectOption('sensor-safari')
  const worksheetDownload=page.waitForEvent('download')
  await page.locator('#teacher-download-worksheet').click()
  const worksheet=await worksheetDownload
  expect(worksheet.suggestedFilename()).toBe('bobo-phieu-sensor-safari.html')
  const worksheetStream=await worksheet.createReadStream(),worksheetChunks=[]
  for await(const chunk of worksheetStream)worksheetChunks.push(chunk)
  const worksheetHtml=Buffer.concat(worksheetChunks).toString('utf8')
  expect(worksheetHtml).toContain('Khoanh, nối, chỉ hoặc vẽ')
  expect(worksheetHtml).toContain('Mã nhóm:')
  expect(worksheetHtml).not.toContain('Tên học sinh')
  const voiceSamples=await page.locator('.teacher-audio-catalog audio').evaluateAll(elements=>elements.map(element=>element.getAttribute('src')))
  expect(voiceSamples).toEqual(['/audio/lessons/grade-1/lesson-01/part-1-theory.mp3','/audio/middle/grade-6/lesson-01/part-1.mp3','/audio/high/grade-10/lesson-01/part-1.mp3'])
  expect(eagerAudioRequests).toEqual([])
  for(const sample of voiceSamples)expect((await page.request.get(new URL(sample,page.url()).href)).ok()).toBe(true)
  await page.locator('#voice-review-primary').check()
  await page.locator('#run-device-check').click()
  await expect(page.locator('.device-capability-status')).toContainText('WebGL')
  await expect(page.locator('.device-capability-status')).toContainText('Camera API')
  await expect(page.locator('.device-capability-status')).toContainText('IndexedDB')
  await expect(page.locator('.device-capability-status')).toContainText('Offline shell')
  await expect(page.locator('.device-readiness li',{hasText:'Bộ nhớ cục bộ'})).toContainText('Sẵn sàng')
  await expect(page.locator('.device-readiness li',{hasText:'IndexedDB'})).toContainText('Sẵn sàng')
  await expect(page.locator('.device-verdict')).toContainText('Sẵn sàng cho pilot kỹ thuật')
  const deviceDownload=page.waitForEvent('download')
  await page.locator('#export-device-check').click()
  const deviceReportDownload=await deviceDownload
  expect(deviceReportDownload.suggestedFilename()).toBe('bobo-kiem-tra-thiet-bi.json')
  const reportStream=await deviceReportDownload.createReadStream(),chunks=[]
  for await(const chunk of reportStream)chunks.push(chunk)
  const deviceReport=JSON.parse(Buffer.concat(chunks).toString('utf8'))
  expect(deviceReport).toMatchObject({format:'bobo-device-readiness-v1',indexedDb:true,storage:true,assessment:{ready:true,blockers:[]},voiceReviews:{primary:{voiceId:'vieneu-trucly',reviewed:true},middle:{reviewed:false},high:{reviewed:false}}})
  expect(deviceReport.viewport.width).toBeGreaterThan(0)
  await page.reload()
  await page.locator('#teacher-tools').click()
  await expect(page.locator('#voice-review-primary')).toBeChecked()
  const evidenceDownload=page.waitForEvent('download')
  await page.getByRole('button',{name:'Xuất gói JSON'}).click()
  const evidenceStream=await (await evidenceDownload).createReadStream(),evidenceChunks=[]
  for await(const chunk of evidenceStream)evidenceChunks.push(chunk)
  const evidenceBundle=JSON.parse(Buffer.concat(evidenceChunks).toString('utf8'))
  expect(evidenceBundle.records.length).toBeGreaterThan(0)
  expect(evidenceBundle.records.every(record=>!('storageWriterId' in record))).toBe(true)
  await page.locator('#teacher-review-record').selectOption({label:'default / default / data-garden'})
  await expect(page.locator('.review-status')).toContainText('✓ Có minh chứng')
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact.uncertaintyChecked).toBe(true)
  expect(artifact.runs).toHaveLength(2)
  expect(artifact.runs.map(run=>run.result.testId)).toEqual(['test-carrot','test-carrot'])
  expect(artifact.runs.map(run=>run.result.label)).toEqual(['fruit','other'])
  expect(artifact.corrections).toContainEqual({id:'radish',from:'fruit',to:'other'})
  await expect(page.locator('.teacher-session-data')).toContainText('Phiên default có 1 bản ghi ở 1 nhóm')
  const sessionDownload=page.waitForEvent('download')
  await page.locator('#export-current-session').click()
  const sessionBackup=await sessionDownload
  expect(sessionBackup.suggestedFilename()).toBe('bobo-phien-default.json')
  const sessionStream=await sessionBackup.createReadStream(),sessionChunks=[]
  for await(const chunk of sessionStream)sessionChunks.push(chunk)
  const sessionBundle=JSON.parse(Buffer.concat(sessionChunks).toString('utf8'))
  expect(sessionBundle).toMatchObject({format:'bobo-evidence-v1',sessionId:'default'})
  expect(sessionBundle.records).toHaveLength(1)
  await page.locator('#start-delete-session').click()
  await page.locator('#delete-session-confirmation').fill('sai')
  await expect(page.locator('#confirm-delete-session')).toBeDisabled()
  await page.locator('#delete-session-confirmation').fill('default')
  await page.locator('#confirm-delete-session').click()
  await expect(page.locator('.teacher-session-data')).toContainText('Đã xóa 1 bản ghi')
  const remaining=await page.evaluate(async()=>{
    const records=await new Promise((resolve,reject)=>{const open=indexedDB.open('bobo-learning',3);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').getAll();request.onsuccess=()=>{db.close();resolve(request.result)}}})
    return {records:records.filter(record=>record.sessionId==='default').length,progress:localStorage.getItem('bobo-progress'),gameProgress:localStorage.getItem('bobo-game-progress')}
  })
  expect(remaining).toEqual({records:0,progress:null,gameProgress:null})
})

test('garden coder dùng dữ liệu quy trình riêng và lưu thứ tự sau khi sửa sai',async({page})=>{
  await page.goto('/#activity=garden-coder')
  await expect(page.getByRole('dialog',{name:'Xếp quy trình học từ ví dụ'})).toBeVisible()
  await expect(page.locator('.mechanic-grid')).toContainText('Thu thập ví dụ')
  await page.locator('#order-step-2').click()
  await expect(page.locator('.game-message')).toContainText('chưa đúng vị trí')
  for(const index of [0,1,2,3])await page.locator(`#order-step-${index}`).click()
  await expect(page.locator('.sequence-track > span')).toHaveCount(4)
  await page.locator('#ai-accept-result').click()
  await expect(page.getByText('HOÀN THÀNH THỬ THÁCH')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / garden-coder'})
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact).toMatchObject({selected:[0,1,2,3],mistakes:1,lastCorrect:true})
})

test('xóa phiên đặt lại tab học sinh và chặn snapshot cũ tạo lại dữ liệu',async({page,context})=>{
  await page.goto('/#activity=garden-coder')
  await page.locator('#order-step-0').click()
  const teacher=await context.newPage()
  await teacher.goto('/tieu-hoc')
  await teacher.locator('#teacher-tools').click()
  await expect(teacher.locator('.teacher-session-data')).toContainText('Phiên default có 1 bản ghi')
  await teacher.locator('#start-delete-session').click()
  await teacher.locator('#delete-session-confirmation').fill('default')
  await teacher.locator('#confirm-delete-session').click()
  await expect(teacher.locator('.teacher-session-data')).toContainText('Các tab đang dùng phiên này được đặt lại tự động')
  await expect(page.getByRole('dialog',{name:'Xếp quy trình học từ ví dụ'})).toHaveCount(0)
  await expect(page.locator('.learning-scope-banner')).toContainText('màn hình học đã đặt lại')
  await expect.poll(()=>page.evaluate(async()=>{
    const records=await new Promise((resolve,reject)=>{const open=indexedDB.open('bobo-learning',3);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').getAll();request.onsuccess=()=>{db.close();resolve(request.result)}}})
    return records.filter(record=>record.sessionId==='default').length
  })).toBe(0)
  await teacher.close()
})

test('giáo viên xuất gói chuẩn bị bài offline có tài nguyên và phiếu đi kèm',async({page})=>{
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-activity-select').selectOption('primary-1-1')
  const download=page.waitForEvent('download')
  await page.locator('#teacher-download-offline-pack').click()
  const pack=await download
  expect(pack.suggestedFilename()).toBe('bobo-goi-offline-primary-1-1.html')
  const stream=await pack.createReadStream(),chunks=[]
  for await(const chunk of stream)chunks.push(chunk)
  const html=Buffer.concat(chunks).toString('utf8')
  expect(html).toContain('GÓI CHUẨN BỊ BÀI OFFLINE')
  expect(html).toContain('Dữ liệu và cấu hình hoạt động')
  expect(html).toContain('/audio/lessons/grade-1/lesson-01/part-1-theory.mp3')
  expect(html).toContain('Phiếu hoạt động đi kèm')
  expect(html).toContain('Phương án không thiết bị')
  expect(html).toContain('Không yêu cầu kiến thức AI trước đó')
  expect(html).toContain('chỉ, chọn hoặc vẽ bằng chứng')
  expect(html).not.toContain('Tên học sinh')
})

test('robot lớp 1 dự đoán, chạy từng bước, bỏ lệnh sai và lưu đường chạy',async({page})=>{
  await page.goto('/#activity=bobo-first-code')
  await expect(page.getByRole('dialog',{name:'Robot tìm đường bằng block'})).toBeVisible()
  await page.locator('#code-block-right2').click()
  await page.locator('#code-block-right').click()
  await page.locator('#predict-cell-3-0').focus()
  await page.keyboard.press('Enter')
  for(let step=0;step<3;step++)await page.locator('#code-step').click()
  await expect(page.locator('.game-message')).toContainText('chưa tới ngôi sao')
  await page.locator('#code-undo').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.game-message')).toContainText('bỏ block cuối')
  await page.locator('#code-block-down').click()
  await page.locator('#predict-cell-2-1').focus()
  await page.keyboard.press('Enter')
  for(let step=0;step<3;step++)await page.locator('#code-step').click()
  await expect(page.getByText('HOÀN THÀNH THỬ THÁCH')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / bobo-first-code'})
  await page.locator('#teacher-observed-explanation').check()
  await page.locator('#save-teacher-observation').click()
  await expect(page.locator('.teacher-observation')).toContainText('✓ Giáo viên đã nghe giải thích')
  await expect(page.locator('.teacher-observation')).toContainText('không thu âm học sinh')
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact).toMatchObject({program:['right2','down'],predictedDestination:[2,1],predictionMatched:true,executionMode:'step-by-step',runs:2,removedBlocks:['right']})
  expect(artifact.positions).toEqual([[0,0],[1,0],[2,0],[2,1]])
})

test('lớp 3 kiểm chứng bằng nội dung đoạn nguồn thay vì tên nguồn',async({page})=>{
  await page.goto('/#activity=evidence-detective')
  await expect(page.getByRole('dialog',{name:'Kiểm chứng trợ lý AI'})).toBeVisible()
  await page.locator('#evidence-source-school-menu').click()
  await page.locator('#evidence-verdict-refuted').click()
  await page.locator('#evidence-submit').click()
  await expect(page.locator('.game-message')).toContainText('không chỉ nhìn tên nguồn')
  await page.locator('#evidence-source-school-schedule').click()
  await page.locator('#evidence-submit').click()
  await expect(page.locator('.claim-card')).toContainText('Cây xanh cần ánh sáng')
  await page.locator('#evidence-source-science-book').click()
  await page.locator('#evidence-verdict-supported').click()
  await page.locator('#evidence-submit').click()
  await page.locator('#evidence-source-ai-guide').click()
  await page.locator('#evidence-verdict-refuted').click()
  await page.locator('#evidence-submit').click()
  for(const [source,verdict] of [['weather-center','supported'],['history-book','supported'],['copyright-guide','refuted']]){
    await page.locator(`#evidence-source-${source}`).click()
    await page.locator(`#evidence-verdict-${verdict}`).click()
    await page.locator('#evidence-submit').click()
  }
  await expect(page.getByText('HOÀN THÀNH KIỂM CHỨNG')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / evidence-detective'})
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact.answers).toHaveLength(6)
  expect(artifact.answers.map(answer=>answer.verdict)).toEqual(['refuted','supported','refuted','supported','supported','refuted'])
  expect(artifact.answers.every(answer=>answer.selectedSource.excerpt.length>20)).toBe(true)
})

test('lớp 5 tách mức đại diện khỏi kết luận công bằng và lưu kết quả nhóm',async({page})=>{
  await page.getByRole('tab',{name:/Lớp 5/}).click()
  await page.locator('#game-5-fair-data-lab').click()
  for(const group of [0,1,2])for(let count=0;count<4;count++)await page.locator(`#balance-add-${group}`).click()
  await page.locator('#balance-check').click()
  await expect(page.locator('.group-audit')).toContainText('8/10 dự đoán đúng')
  await expect(page.locator('.group-audit')).toContainText('6/10 dự đoán đúng')
  await expect(page.locator('.game-message')).toContainText('Chia đều chưa tự động đảm bảo công bằng')
  await expect(page.locator('#accept-representation-audit')).toBeVisible()
  await expect(page.getByText('HOÀN THÀNH THỬ THÁCH')).toHaveCount(0)
  await page.locator('#accept-representation-audit').click()
  await expect(page.getByText('HOÀN THÀNH THỬ THÁCH')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / fair-data-lab'})
  await expect(page.locator('.review-status')).toContainText('✓ Có minh chứng')
  await page.locator('.teacher-artifact summary').click()
  await expect(page.locator('#teacher-artifact')).toContainText('"auditResults"')
  await expect(page.locator('#teacher-artifact')).toContainText('"accuracy": 60')
})

test('pipeline lớp 5 lưu và so sánh phiên bản A B',async({page})=>{
  await page.goto('/#activity=ai-pipeline-code')
  for(const id of ['problem','data','train','improve'])await page.locator(`#primary-stage-${id}`).click()
  await page.locator('#primary-pipeline-run').click()
  await expect(page.locator('.primary-run-grid article')).toHaveCount(1)
  await expect(page.locator('.primary-run-grid')).toContainText('chưa có bước kiểm thử')
  await page.locator('#close-game').click()
  await page.locator('#game-5-ai-pipeline-code').click()
  await expect(page.locator('.primary-run-grid article')).toHaveCount(1)
  await page.locator('#primary-stage-test').click()
  await page.locator('#primary-stage-up-test').click()
  for(let count=0;count<4;count++)await page.locator('#primary-data-add-2').click()
  await page.locator('#primary-pipeline-run').click()
  await expect(page.locator('.primary-run-grid article')).toHaveCount(2)
  await expect(page.locator('.primary-run-grid')).toContainText('Pipeline đủ bước và dữ liệu có cả ba nhóm')
  await page.locator('#primary-pipeline-reflection').fill('Em thêm kiểm thử theo nhóm và bổ sung bốn mẫu cho nhóm C.')
  await page.locator('#finish-primary-pipeline').click()
  await expect(page.getByText('HOÀN THÀNH PIPELINE A/B')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / ai-pipeline-code'})
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact.runs).toHaveLength(2)
  expect(artifact.runs[0]).toMatchObject({pipeline:['problem','data','train','improve'],counts:[4,4,0]})
  expect(artifact.runs[1]).toMatchObject({pipeline:['problem','data','train','test','improve'],counts:[4,4,4]})
  expect(artifact.reflection).toContain('nhóm C')
})

test('lớp 4 huấn luyện mô hình lá hai lần và lưu minh chứng so sánh',async({page})=>{
  await page.getByRole('tab',{name:/Lớp 4/}).click()
  await page.locator('#game-4-shield-coder').click()
  await expect(page.locator('.leaf-lab-modal')).toContainText('TensorFlow.js chạy trên thiết bị')
  await page.locator('#train-leaf-model').click()
  await expect(page.locator('.leaf-runs>article')).toHaveCount(1,{timeout:45000})
  await expect(page.locator('#finish-leaf-lab')).toBeDisabled()
  await page.locator('#leaf-label-leaf-1').click()
  await expect(page.locator('#train-leaf-model')).toContainText('Huấn luyện lần 2')
  await page.locator('#train-leaf-model').click()
  await expect(page.locator('.leaf-runs>article')).toHaveCount(2,{timeout:45000})
  await expect(page.locator('.leaf-predictions')).toHaveCount(2)
  await page.locator('#leaf-reflection').fill('Đổi một nhãn đã làm kết quả trên cùng mẫu kiểm thử thay đổi.')
  await page.locator('#finish-leaf-lab').click()
  await expect(page.getByText('HOÀN THÀNH PHÒNG LAB')).toBeVisible()
  await page.locator('#game-finish').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / shield-coder'})
  await expect(page.locator('.review-status')).toContainText('✓ Có minh chứng')
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact.runs).toHaveLength(2)
  expect(artifact.runs[0].datasetSignature).not.toBe(artifact.runs[1].datasetSignature)
  expect(artifact.runs.map(run=>run.predictions.map(item=>item.id))).toEqual([['test-healthy','test-sick'],['test-healthy','test-sick']])
  expect(artifact.runs.every(run=>run.config.epochs===100&&run.config.seed===42)).toBe(true)
})

test('lab giữ lượt cũ khi làm lại và lưu thao tác trước khi đóng',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#open-pipeline-lab').click()
  await page.locator('#pipeline-block-problem').click()
  await page.getByRole('button',{name:'Làm lại',exact:true}).click()
  await page.locator('#pipeline-block-data').click()
  await page.locator('#close-middle-lab').click()
  await page.locator('#open-pipeline-lab').click()
  await expect(page.locator('.block-program')).toContainText('Thu thập dữ liệu')
  await expect.poll(()=>page.evaluate(async()=>{
    const db=await new Promise((resolve,reject)=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})
    const record=await new Promise((resolve,reject)=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').get(JSON.stringify(['default','default','middle-6-life']));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})
    db.close()
    return {attempts:record?.attempts,previous:record?.attemptHistory?.[0]?.data?.program,current:record?.data?.program}
  })).toEqual({attempts:2,previous:['problem'],current:['data']})
})

test('tab cũ không ghi đè hoạt động đã được tab khác cập nhật',async({page,context})=>{
  await page.goto('/thcs')
  await page.locator('#open-pipeline-lab').click()
  const second=await context.newPage()
  await second.goto('/thcs')
  await second.locator('#open-pipeline-lab').click()
  await second.locator('#pipeline-block-data').click()
  await expect.poll(()=>second.evaluate(async()=>{
    const db=await new Promise((resolve,reject)=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})
    const record=await new Promise((resolve,reject)=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').get(JSON.stringify(['default','default','middle-6-life']));request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})
    db.close();return record?.data?.program
  })).toEqual(['data'])
  await page.locator('#pipeline-block-problem').click()
  await expect(page.getByRole('alert')).toContainText('đã thay đổi ở tab khác')
  await page.reload()
  await page.locator('#open-pipeline-lab').click()
  await expect(page.locator('.block-program')).toContainText('Thu thập dữ liệu')
  await expect(page.locator('.block-program')).not.toContainText('Xác định vấn đề')
  await second.close()
})

test('pipeline mô phỏng dòng dữ liệu và chặn rò rỉ test vào train',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#open-pipeline-lab').click()
  for(const id of ['problem','data','train','test','human'])await page.locator(`#pipeline-block-${id}`).click()
  await page.locator('#pipeline-leak-test').check()
  await page.locator('#run-pipeline').click()
  await expect(page.locator('.lab-message')).toContainText('Rò rỉ dữ liệu')
  await expect(page.locator('#pipeline-data-trace')).toContainText('test-new-1')
  await expect(page.getByText('Pipeline đã chạy thành công!')).toHaveCount(0)
  await page.locator('#pipeline-leak-test').uncheck()
  await page.locator('#run-pipeline').click()
  await expect(page.getByText('Pipeline đã chạy thành công!')).toBeVisible()
})

test('lớp 9 xuất artifact liên kết pipeline model test và canvas',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#middle-grade-9').click()
  await page.locator('#open-pipeline-lab').click()
  for(const id of ['problem','data','train','test','human'])await page.locator(`#pipeline-block-${id}`).click()
  await page.locator('#run-pipeline').click()
  await expect(page.getByText('Pipeline đã chạy thành công!')).toHaveCount(0)
  await page.locator('#grade9-model-config').selectOption('linear-small')
  await page.locator('#grade9-problem').fill('Phân loại lá để hỗ trợ học sinh khảo sát vườn trường.')
  await page.locator('#grade9-dataDecision').fill('Dùng bốn ID train và giữ hai ID test độc lập để đánh giá.')
  await page.locator('#grade9-explanation').fill('Kết quả chỉ áp dụng cho dữ liệu mẫu và cần người kiểm tra giới hạn.')
  for(const id of ['normal','missingSource','failure'])await page.locator(`#grade9-test-${id}`).check()
  const download=page.waitForEvent('download')
  await page.locator('#export-grade9-project').click()
  expect((await download).suggestedFilename()).toBe('bobo-grade-9-project.json')
  await page.locator('#finish-grade9-project').click()
  await expect(page.getByText('Pipeline đã chạy thành công!')).toBeVisible()
})

test('lab lớp 9 có nhãn điều khiển và focus bàn phím',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#middle-grade-9').click()
  await page.locator('#open-pipeline-lab').click()
  const results=await new AxeBuilder({page}).include('.grade9-project').analyze()
  expect(results.violations.filter(item=>['critical','serious'].includes(item.impact))).toEqual([])
  await page.locator('#grade9-model-config').focus()
  await expect(page.locator('#grade9-model-config')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.locator('#grade9-problem')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.locator('#grade9-dataDecision')).toBeFocused()
})

test('ML lớp 8 so sánh FP FN ở hai ngưỡng trên cùng tập test',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#middle-grade-8').click()
  await page.locator('#open-studio-lab').click()
  for(let count=0;count<2;count++){
    await page.locator('#add-healthy').click()
    await page.locator('#add-sick').click()
  }
  await page.locator('#train-visual-model').click()
  await expect(page.locator('#evaluate-ml-threshold')).toBeVisible({timeout:20000})
  await expect(page.locator('.ml-code-preview')).toContainText('CHƯA PHẢI TEST ACC')
  await page.locator('#evaluate-ml-threshold').click()
  const lowThreshold=await page.locator('#ml-confusion-matrix').innerText()
  expect(lowThreshold).toContain('FP')
  expect(lowThreshold).toContain('FN')
  await page.locator('#ml-threshold').fill('0.7')
  await page.locator('#evaluate-ml-threshold').click()
  await expect(page.locator('#finish-ml-studio')).toBeVisible()
  const highThreshold=await page.locator('#ml-confusion-matrix').innerText()
  expect(highThreshold).not.toBe(lowThreshold)
  await page.locator('#finish-ml-studio').click()
  await expect(page.getByText('Mô hình đã được kiểm thử!')).toBeVisible()
})

test('ML lớp 6 đọc đúng sai trên hai ID kiểm thử',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#open-studio-lab').click()
  await page.locator('#ml-green-healthy-1').fill('0.55')
  await page.locator('#ml-label-healthy-1').selectOption('sick')
  await expect(page.locator('.studio-tip')).toContainText('ít nhất 4 mẫu')
  await page.locator('#close-middle-lab').click()
  await page.locator('#open-studio-lab').click()
  await expect(page.locator('#ml-green-healthy-1')).toHaveValue('0.55')
  await expect(page.locator('#ml-label-healthy-1')).toHaveValue('sick')
  await page.locator('#ml-label-healthy-1').selectOption('healthy')
  for(let count=0;count<2;count++){
    await page.locator('#add-healthy').click()
    await page.locator('#add-sick').click()
  }
  await page.locator('#train-visual-model').click()
  await expect(page.locator('#test-healthy')).toBeVisible({timeout:20000})
  await page.locator('#test-healthy').click()
  await expect(page.locator('.prediction-zone aside')).toContainText(/Đúng:|Sai:/)
  await expect(page.locator('#grade-6-test-result')).toContainText('1/2 ID')
  await page.locator('#test-healthy').click()
  await expect(page.locator('#grade-6-test-result')).toContainText('1/2 ID')
  await page.locator('#test-sick').click()
  await expect(page.locator('#grade-6-test-result')).toContainText('2/2 ID')
  await expect(page.locator('#finish-ml-studio')).toBeVisible()
})

test('Prompt Lab kiểm ba ca hữu hạn trước khi hoàn thành pipeline',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#open-code-lab').click()
  await page.locator('#prompt-case-missing-context').click()
  await expect(page.locator('.prompt-output')).toContainText('CẦN BỔ SUNG')
  await page.locator('#prompt-case-private-data').click()
  await expect(page.locator('.prompt-output')).toContainText('CHẶN DỮ LIỆU RIÊNG TƯ')
  await page.locator('#prompt-case-out-of-scope').click()
  await expect(page.locator('.prompt-output')).toContainText('TỪ CHỐI NGOÀI PHẠM VI')
  await page.locator('#code-mode').click()
  for(const id of ['input','filter','model','verify'])await page.locator(`#code-pipeline-${id}`).click()
  await page.locator('#run-safe-code').click()
  await expect(page.getByText('Pipeline an toàn đã sẵn sàng!')).toBeVisible()
  await page.locator('#finish-middle-lab').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#teacher-review-record').selectOption({label:'default / default / middle-6-prompt'})
  await page.locator('.teacher-artifact summary').click()
  const artifact=JSON.parse(await page.locator('#teacher-artifact').textContent())
  expect(artifact.codePassed).toBe(true)
  expect(artifact.promptRuns.map(run=>run.outcome)).toEqual(['ask-context','block-private','refuse-scope'])
})

test('Bias Lab chọn biện pháp và lưu số liệu trước sau',async({page})=>{
  await page.goto('/thcs')
  await page.locator('#open-game-lab').click()
  for(const [round,answer] of [[0,0],[1,1],[2,1]])await page.locator(`#bias-answer-${round}-${answer}`).click()
  await expect(page.locator('#recalculate-bias')).toBeVisible()
  await expect(page.getByText('Phá án AI thành công!')).toHaveCount(0)
  await page.locator('#bias-measure-more-data').click()
  await page.locator('#recalculate-bias').click()
  await expect(page.locator('#bias-before-after')).toContainText('61% → 78%')
  await expect(page.locator('.bias-game')).toContainText('chưa đủ kết luận công bằng ngoài thực tế')
  await page.locator('#finish-bias-audit').click()
  await expect(page.getByText('Phá án AI thành công!')).toBeVisible()
})

test('migration v2 và ba nhóm giữ riêng pipeline sau chuyển nhóm và reload',async({page})=>{
  const errors=[]
  page.on('pageerror',error=>errors.push(error.message))
  await page.evaluate(async()=>{
    const db=await new Promise((resolve,reject)=>{
      const request=indexedDB.open('bobo-learning',2)
      request.onupgradeneeded=()=>request.result.createObjectStore('activity-evidence',{keyPath:'activityId'})
      request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)
    })
    await new Promise((resolve,reject)=>{
      const tx=db.transaction('activity-evidence','readwrite')
      tx.objectStore('activity-evidence').put({activityId:'middle-6-life',version:3,schemaVersion:2,status:'active',attempts:1,mistakes:0,hintsUsed:0,score:null,data:{program:['problem'],testInTrain:false,trace:[],mistakes:0,message:'',completed:false},events:[],evidence:[],updatedAt:1})
      tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error)
    })
    db.close()
  })
  await page.goto('/thcs')
  await page.locator('#open-pipeline-lab').click()
  await expect(page.locator('#pipeline-block-problem')).toBeDisabled()
  await page.locator('#pipeline-block-data').click()
  await page.locator('#close-middle-lab').click()
  const switchGroup=async(group)=>{
    await page.locator('#teacher-tools').click()
    await page.locator('#learning-session').fill('lesson-7')
    await page.locator('#learning-group').fill(group)
    await page.locator('#apply-learning-scope').click()
    await expect(page.locator('.learning-scope-banner')).toContainText(`Nhóm: ${group}`)
    await page.locator('.teacher-close').click()
    await page.locator('#open-pipeline-lab').click()
  }
  await switchGroup('A')
  await expect(page.locator('.block-program article')).toHaveCount(0)
  await page.locator('#pipeline-block-train').click()
  await page.locator('#close-middle-lab').click()
  await switchGroup('B')
  await expect(page.locator('.block-program article')).toHaveCount(0)
  await page.locator('#pipeline-block-test').click()
  await page.locator('#close-middle-lab').click()
  await switchGroup('A')
  await expect(page.locator('#pipeline-block-train')).toBeDisabled()
  await expect(page.locator('#pipeline-block-test')).toBeEnabled()
  await page.reload()
  await page.locator('#open-pipeline-lab').click()
  await expect(page.locator('#pipeline-block-train')).toBeDisabled()
  await expect.poll(()=>page.evaluate(async()=>{
    const db=await new Promise(resolve=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result)})
    const read=store=>new Promise(resolve=>{const request=db.transaction(store).objectStore(store).getAll();request.onsuccess=()=>resolve(request.result)})
    const records=await read('scoped-activity-evidence'),legacy=await read('activity-evidence')
    db.close()
    return {records:records.map(r=>({group:r.learnerOrGroupId,program:r.data.program})).sort((a,b)=>a.group.localeCompare(b.group)),legacy:legacy[0].data.program}
  })).toEqual({records:[{group:'A',program:['train']},{group:'B',program:['test']},{group:'default',program:['problem','data']}],legacy:['problem']})
  expect(errors).toEqual([])
})

test('nhập minh chứng xem trước, hủy, giữ bản trùng và tách phiên nguồn',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/thcs')
  await page.locator('#open-pipeline-lab').click()
  await page.locator('#pipeline-block-problem').click()
  await page.locator('#close-middle-lab').click()
  await page.locator('#teacher-tools').click()
  const base={activityId:'middle-6-life',version:2,status:'active',attempts:1,mistakes:0,hintsUsed:0,score:null,data:{program:['test'],mistakes:0,completed:false,message:''},events:[],evidence:[]}
  const records=[base,{...base,sessionId:'source2',learnerOrGroupId:'B'}]
  const upload=()=>page.locator('#evidence-file').setInputFiles({name:'evidence.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'bobo-evidence-v1',records}))})
  const read=()=>page.evaluate(async()=>{
    const db=await new Promise(resolve=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result)})
    const records=await new Promise(resolve=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').getAll();request.onsuccess=()=>resolve(request.result)})
    db.close();return records
  })
  await upload()
  await expect(page.locator('.evidence-import')).toContainText('Chưa lưu vào máy')
  expect((await read()).length).toBe(1)
  await page.locator('#preview-evidence').click()
  await expect(page.locator('.evidence-preview')).toContainText('Sẽ thêm 1 bản ghi; giữ 1 bản trùng')
  await page.getByRole('button',{name:'Hủy nhập',exact:true}).click()
  expect((await read()).length).toBe(1)
  await upload()
  await page.locator('#preview-evidence').click()
  await page.locator('#confirm-evidence-import').click()
  await expect(page.locator('.evidence-import')).toContainText('Đã nhập 1 bản ghi')
  let saved=await read()
  expect(saved).toHaveLength(2)
  expect(saved.find(r=>r.learnerOrGroupId==='default').data.program).toEqual(['problem'])
  expect(saved.find(r=>r.learnerOrGroupId==='B').data.program).toEqual(['test'])
  await upload()
  await page.locator('#evidence-policy').selectOption('new-session')
  await page.locator('#evidence-session-prefix').fill('import-check')
  await page.locator('#preview-evidence').click()
  await expect(page.locator('.evidence-preview')).toContainText('import-check-2 / B')
  await page.locator('#confirm-evidence-import').click()
  await expect(page.locator('.evidence-import')).toContainText('Đã nhập 2 bản ghi')
  saved=await read()
  expect(saved).toHaveLength(4)
  expect(saved.filter(r=>r.sessionId.startsWith('import-check')).map(r=>r.sessionId).sort()).toEqual(['import-check-1','import-check-2'])
  expect(errors).toEqual([])
})

test('nhập minh chứng rollback cả gói khi ghi bản thứ hai bị lỗi',async({page})=>{
  await page.locator('#teacher-tools').click()
  const base={version:1,status:'active',attempts:1,mistakes:0,hintsUsed:0,score:null,data:{},events:[],evidence:[]}
  const records=['atomic-a','atomic-b'].map(activityId=>({...base,activityId}))
  await page.locator('#evidence-file').setInputFiles({name:'atomic.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'bobo-evidence-v1',records}))})
  await page.locator('#preview-evidence').click()
  await expect(page.locator('.evidence-preview')).toContainText('Sẽ thêm 2 bản ghi')
  await page.evaluate(()=>{
    const put=IDBObjectStore.prototype.put
    IDBObjectStore.prototype.put=function(value,...args){
      if(this.name==='scoped-activity-evidence'&&value.activityId==='atomic-b')throw new DOMException('Simulated quota failure','QuotaExceededError')
      return put.call(this,value,...args)
    }
  })
  await page.locator('#confirm-evidence-import').click()
  await expect(page.locator('.evidence-import')).toContainText('Không nhập được gói')
  const count=await page.evaluate(async()=>{
    const db=await new Promise(resolve=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result)})
    const result=await new Promise(resolve=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').count();request.onsuccess=()=>resolve(request.result)})
    db.close();return result
  })
  expect(count).toBe(0)
  await expect(page.locator('#confirm-evidence-import')).toHaveCount(0)
})

test('TeacherDock mở đúng bài học và công cụ thực hành ở cả ba cấp',async({page})=>{
  const errors=[]
  page.on('pageerror',error=>errors.push(error.message))
  const cases=[
    {path:'/',lesson:'primary-1-1',lessonClose:'#close-lesson',tool:'sensor-safari',toolClose:'#close-game'},
    {path:'/thcs',lesson:'middle-6-lesson-1',lessonClose:'#close-middle-lesson',tool:'middle-6-life',toolClose:'#close-middle-lab'},
    {path:'/thpt',lesson:'high-10-lesson-1',lessonClose:'#close-high-lesson',tool:'high-10-systems',toolClose:'#close-high-lab'}
  ]
  for(const item of cases){
    await page.goto(item.path)
    for(const [activityId,closeSelector] of [[item.lesson,item.lessonClose],[item.tool,item.toolClose]]){
      await page.locator('#teacher-tools').click()
      await page.locator('#teacher-activity-select').selectOption(activityId)
      await page.locator('#teacher-open-activity').click()
      await expect(page.locator(closeSelector)).toBeVisible({timeout:10000})
      await expect(page).toHaveURL(new RegExp(`activity=${activityId}`))
      await page.locator(closeSelector).click()
    }
  }
  expect(errors).toEqual([])
})

test('bài học ba cấp tạo artifact để giáo viên xem và tách theo nhóm',async({page})=>{
  test.setTimeout(60000)
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  const readRecord=activityId=>page.evaluate(async activityId=>{
    const db=await new Promise(resolve=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result)})
    const record=await new Promise(resolve=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').get(JSON.stringify(['default','default',activityId]));request.onsuccess=()=>resolve(request.result)})
    db.close();return record?{status:record.status,evidence:record.evidence.length,artifact:record.evidence.at(-1)?.data}:null
  },activityId)
  const inspectArtifact=async(activityId,expected,marker)=>{
    await expect.poll(()=>readRecord(activityId)).toMatchObject({status:'complete',evidence:2,artifact:expected})
    await page.locator('#teacher-tools').click()
    await page.locator('#teacher-review-record').selectOption({label:`default / default / ${activityId}`})
    await page.locator('.teacher-artifact summary').click()
    await expect(page.locator('#teacher-artifact')).toContainText('"quizCorrect": true')
    await expect(page.locator('#teacher-artifact')).toContainText(marker)
    expect(await page.locator('#teacher-artifact').evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true)
    await page.locator('.teacher-close').click()
  }

  await page.goto('/tieu-hoc')
  await page.locator('#lesson-1-1').click()
  for(let step=0;step<3;step++)await page.locator('#next-lesson-slide').click()
  let primaryAnswer
  for(let answer=0;answer<3;answer++){
    await page.locator(`#lesson-answer-${answer}`).click()
    if(await page.locator('#complete-lesson').isEnabled()){primaryAnswer=answer;break}
  }
  await page.locator('#complete-lesson').click()
  await page.locator('#close-lesson').click()
  await inspectArtifact('primary-1-1',{quizCorrect:true},'"partsViewed": 4')

  await page.goto('/thcs')
  await page.locator('#middle-lesson-6-1').click()
  await expect(page.locator('#middle-lesson-title')).toHaveText('AI là một hệ thống')
  await expect(page.locator('.lesson-dialog>header')).toContainText('Lớp 6 thực hành ở mức')
  await page.locator('#middle-lesson-next').click()
  await page.locator('#middle-slide-next').click()
  await expect(page.locator('.lesson-practice')).toContainText('Làm theo khung: AI là một hệ thống')
  for(const block of [2,0,1])await page.locator(`#lesson-practice-${block}`).click()
  await page.locator('#middle-practice-next').click()
  await expect(page.locator('.middle-quiz')).toContainText('sơ đồ có đủ đầu vào')
  await page.locator('#middle-answer-0').click()
  await page.locator('#complete-middle-lesson').click()
  await page.locator('#finish-middle-lesson').click()
  await inspectArtifact('middle-6-lesson-1',{quizCorrect:true},'"variantRef": "middle-6-lesson-1"')

  await page.goto('/thpt')
  await page.locator('#high-lesson-10-1').click()
  for(let step=0;step<3;step++)await page.locator('#next-high-step').click()
  for(let answer=0;answer<3;answer++){
    await page.locator(`#high-answer-${answer}`).click()
    if(await page.locator('#complete-high-lesson').isEnabled())break
  }
  await page.locator('#complete-high-lesson').click()
  await page.locator('#close-high-lesson').click()
  await inspectArtifact('high-10-lesson-1',{quizCorrect:true},'"practicePrompt"')

  await page.goto('/tieu-hoc')
  await page.locator('#teacher-tools').click()
  await page.locator('#learning-group').fill('B')
  await page.locator('#apply-learning-scope').click()
  await page.locator('.teacher-close').click()
  await expect(page.locator('#lesson-1-1')).not.toHaveClass(/done/)
  expect(await page.evaluate(async()=>{
    const db=await new Promise(resolve=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result)})
    const record=await new Promise(resolve=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').get(JSON.stringify(['default','B','primary-1-1']));request.onsuccess=()=>resolve(request.result)})
    db.close();return record
  })).toBeUndefined()
  expect(primaryAnswer).toBeGreaterThanOrEqual(0)
  expect(errors).toEqual([])
})

test('giáo viên chấm rubric theo minh chứng và đúng lượt thử',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/thcs')
  await page.locator('#open-pipeline-lab').click()
  for(const id of ['problem','data','train','test','human'])await page.locator(`#pipeline-block-${id}`).click()
  await page.locator('#run-pipeline').click()
  await expect(page.getByText('THỬ THÁCH HOÀN THÀNH')).toBeVisible()
  await page.locator('#finish-middle-lab').click()
  await expect.poll(()=>page.evaluate(async()=>{
    const db=await new Promise(resolve=>{const request=indexedDB.open('bobo-learning');request.onsuccess=()=>resolve(request.result)})
    const record=await new Promise(resolve=>{const request=db.transaction('scoped-activity-evidence').objectStore('scoped-activity-evidence').get(JSON.stringify(['default','default','middle-6-life']));request.onsuccess=()=>resolve(request.result)})
    db.close();return record?.status
  })).toBe('complete')
  await page.locator('#teacher-tools').click()
  await expect(page.locator('.review-status')).toContainText('✓ Hoàn thành')
  await expect(page.locator('.review-status')).toContainText('✓ Có minh chứng')
  await expect(page.locator('.review-status')).toContainText('○ Chưa đánh giá')
  for(const [key,value] of [['modeling','2'],['testing','3'],['explanation','2'],['responsibility','1']])await page.locator(`#teacher-rating-${key}`).selectOption(value)
  await page.locator('#teacher-review-note').fill('Nhóm giải thích được kết quả và cần nêu thêm giới hạn.')
  await page.locator('#save-teacher-review').click()
  await expect(page.locator('.review-status')).toContainText('✓ Đã đánh giá')
  await expect(page.locator('.teacher-report>div').first()).toContainText('1 đã đánh giá')
  await page.locator('.teacher-close').click()
  await page.reload()
  await page.locator('#teacher-tools').click()
  await expect(page.locator('#teacher-rating-testing')).toHaveValue('3')
  await expect(page.locator('#teacher-review-note')).toHaveValue(/cần nêu thêm giới hạn/)
  await expect(page.locator('.review-status')).toContainText('✓ Đã đánh giá')
  await page.locator('.teacher-close').click()
  await page.locator('#open-pipeline-lab').click()
  await page.locator('#replay-middle-lab').click()
  await page.locator('#close-middle-lab').click()
  await page.locator('#teacher-tools').click()
  await expect(page.locator('.review-status')).toContainText('○ Chưa đánh giá')
  expect(errors).toEqual([])
})

test('ba cấp vẫn mở khi tiến độ JSON hỏng và giữ bản phục hồi',async({page})=>{
  const errors=[]
  page.on('pageerror',error=>errors.push(error.message))
  for(const [path,key] of [['/','bobo-progress'],['/thcs','bobo-thcs-progress'],['/thpt','bobo-thpt-progress']]) {
    await page.evaluate(key=>localStorage.setItem(key,'{broken'),key)
    await page.goto(path)
    await expect(page.locator('h1')).toBeVisible()
    await expect(page.getByRole('alert')).toContainText('Tiến độ không đọc được')
    expect(await page.evaluate(key=>Object.keys(localStorage).some(item=>item.startsWith(`${key}:recovery:`)&&localStorage.getItem(item)==='{broken'),key)).toBe(true)
  }
  expect(errors).toEqual([])
})

test('RAG mở đoạn nguồn và lưu hai phép thử có và thiếu tài liệu',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/thpt')
  await page.locator('#high-grade-11').click()
  await page.locator('#open-high-genai').click()
  await expect(page.locator('#sampling-title')).toContainText('Lớp 11')
  await page.locator('#run-genai').click()
  await expect(page.locator('#record-rag-run')).toBeDisabled()
  await page.locator('#rag-citation-plant').click()
  await page.locator('#record-rag-run').click()
  await page.locator('#sampling-temperature').fill('0.2')
  await page.locator('#sample-token').click()
  await page.locator('#sample-token').click()
  await expect(page.locator('#sampling-history li')).toHaveCount(2)
  await expect(page.locator('#finish-genai')).toBeDisabled()
  await page.locator('#close-high-lab').click()
  await page.locator('#open-high-genai').click()
  await page.locator('#rag-run-0').click()
  await expect(page.locator('.genai-lab blockquote')).toContainText('carbon dioxide')
  for(const viewport of [{width:390,height:844},{width:768,height:1024},{width:1440,height:900}]) {
    await page.setViewportSize(viewport)
    await expect(page.locator('#genai-prompt')).toBeVisible()
    expect(await page.locator('.genai-lab').evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true)
  }
  await page.locator('#genai-prompt').fill('Thuật toán sắp xếp là gì?')
  await page.locator('#run-genai').click()
  await expect(page.locator('.genai-lab').getByRole('status')).toContainText('Chưa đủ bằng chứng')
  await page.locator('#record-rag-run').click()
  await page.locator('#sampling-temperature').fill('1.2')
  await page.locator('#sampling-example').check()
  await page.locator('#sample-token').click()
  await page.locator('#sample-token').click()
  await expect(page.locator('#sampling-history li')).toHaveCount(4)
  await expect(page.locator('#sampling-history')).toContainText('T=0.2 · không ví dụ')
  await expect(page.locator('#sampling-history')).toContainText('T=1.2 · có ví dụ')
  await expect(page.locator('#finish-genai')).toBeDisabled()
  await page.locator('#genai-reflection').fill('Temperature cao làm phân bố bớt tập trung; ví dụ đổi xác suất, còn nguồn RAG vẫn cần được kiểm tra.')
  await page.locator('#finish-genai').click()
  await expect(page.getByText('LAB COMPLETED')).toBeVisible()
  await page.locator('#close-complete-high').click()
  await page.locator('#teacher-tools').click()
  await expect(page.locator('.rubric-guide').first()).toContainText('temperature, few-shot và RAG')
  await expect(page.locator('.rubric-guide').nth(1)).toContainText('hai temperature và ca đủ/thiếu nguồn')
  await page.locator('.teacher-artifact summary').click()
  await expect(page.locator('#teacher-artifact')).toContainText('Temperature cao làm phân bố')
  expect(errors).toEqual([])
})

test('GenAI phân hóa nhiệm vụ và dữ liệu theo lớp 10–12',async({page})=>{
  const cases=[
    {grade:10,title:'dữ liệu an toàn',prompt:'số điện thoại',source:'privacy'},
    {grade:11,title:'temperature, few-shot và RAG',prompt:'quang hợp',source:'plant'},
    {grade:12,title:'guardrail và giám sát',prompt:'khiếu nại',source:'governance'}
  ]
  for(const item of cases){
    await page.goto('/thpt')
    await page.locator(`#high-grade-${item.grade}`).click()
    await page.locator('#open-high-genai').click()
    await expect(page.locator('#sampling-title')).toContainText(`Lớp ${item.grade}`)
    await expect(page.locator('#sampling-title')).toContainText(item.title)
    await expect(page.locator('#genai-prompt')).toHaveValue(new RegExp(item.prompt,'i'))
    await expect(page.locator(`#rag-source-${item.source}`)).toBeChecked()
  }
})

test('Data Lab lớp 12 train thật, khảo sát ngưỡng và phát hiện drift',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/thpt')
  await page.locator('#high-grade-12').click()
  await page.locator('#open-high-data').click()
  await page.locator('#clean-data').click()
  await expect(page.getByText(/Giá trị thay thế:/)).toContainText('4.70')
  await page.locator('#run-data').click()
  await page.locator('#train-data-model').click()
  await expect(page.locator('#regression-mae')).toBeVisible({timeout:25000})
  await expect(page.locator('.training-benchmark')).toContainText(/Benchmark thiết bị: \d+ ms · backend (cpu|webgl|wasm)/)
  const mae=await page.locator('#regression-mae').textContent()
  await page.locator('#classification-threshold').fill('8')
  await expect(page.locator('#regression-mae')).toHaveText(mae)
  await page.locator('#close-high-lab').click()
  await page.locator('#open-high-data').click()
  await expect(page.locator('#classification-threshold')).toHaveValue('8')
  await page.locator('#study-feature-set').selectOption('hours-missing')
  await expect(page.locator('#regression-mae')).toHaveCount(0)
  await page.locator('#close-high-lab').click()
  await page.locator('#open-high-data').click()
  await expect(page.locator('#study-feature-set')).toHaveValue('hours-missing')
  await page.locator('#data-r1-hours').fill('8')
  await page.locator('#data-r1-group').fill('Nhóm mới')
  await expect(page.locator('#regression-mae')).toHaveCount(0)
  await page.locator('#close-high-lab').click()
  await page.locator('#open-high-data').click()
  await expect(page.locator('#data-r1-hours')).toHaveValue('8')
  await expect(page.locator('#data-r1-group')).toHaveValue('Nhóm mới')
  await page.locator('#clean-data').click()
  await page.locator('#run-data').click()
  await page.locator('#train-data-model').click()
  await expect(page.locator('#regression-mae')).toBeVisible({timeout:25000})
  await expect(page.locator('.data-run-history article')).toHaveCount(2)
  await expect(page.locator('.data-run-history')).toContainText('hours + hoursMissing')
  await expect(page.locator('.data-run-history')).toContainText('seed 42')
  await expect(page.locator('.training-benchmark')).toContainText(/\d+ ms/)
  await expect(page.locator('#finish-data-lab')).toBeDisabled()
  await page.locator('#check-data-drift').click()
  await expect(page.locator('.drift-lab')).toContainText('MAE sau drift')
  await expect(page.locator('.drift-lab')).toContainText('ngoại lệ lớn nhất')
  await expect(page.locator('.drift-lab')).toContainText('Không suy rộng hiệu quả')
  await page.locator('#drift-monitor').selectOption('human-review')
  await page.locator('#finish-data-lab').click()
  await expect(page.getByText('LAB COMPLETED')).toBeVisible()
  expect(errors).toEqual([])
})

test('CSV nhập hợp lệ, từ chối dữ liệu lỗi và giữ dataset sau mở lại',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/thpt')
  await page.locator('#open-high-data').click()
  const input=page.locator('.data-lab input[type=file]')
  const upload=text=>input.setInputFiles({name:'study.csv',mimeType:'text/csv',buffer:Buffer.from(text)})
  await upload('id,group,hours,score\nr1,A,4,8\nnewtest,B,NA,6')
  await expect(page.locator('#data-newtest-score')).toHaveValue('6')
  await expect(page.locator('.data-output header')).toContainText('2 mẫu · 1 train / 1 test')
  for(const body of ['r1,A,NA,8\nr2,B,3,7','r1,A,2,8\nr3,B,3,7','r1,A,2,\nr2,B,3,7']) {
    await upload('id,group,hours,score\n'+body)
    await expect(page.locator('.data-lab [role=alert]')).toBeVisible()
    await expect(page.locator('#data-newtest-score')).toHaveValue('6')
  }
  await upload('x'.repeat(65537))
  await expect(page.locator('.data-lab [role=alert]')).toContainText('64 KiB')
  await page.locator('#close-high-lab').click()
  await page.locator('#open-high-data').click()
  await expect(page.locator('#data-newtest-score')).toHaveValue('6')
  expect(errors).toEqual([])
})

test('camera dùng luồng giả lập và không gửi ảnh',async({page,browserName})=>{
  test.skip(browserName==='webkit','Playwright WebKit không hỗ trợ fake camera; kiểm camera Safari trên thiết bị thật trước pilot.')
  const requests=[]
  page.on('request',request=>requests.push(request.url()))
  await page.locator('#try-camera').click()
  await page.locator('#open-camera').click()
  await expect(page.locator('#recognize-object')).toBeVisible()
  expect(requests.some(url=>/upload|predict|classify/i.test(url)&&!url.startsWith(page.url().split('/').slice(0,3).join('/')))).toBe(false)
})

test('tab giáo viên tắt camera và audio đang chạy trên tab học sinh',async({page,context,browserName})=>{
  test.skip(browserName==='webkit','Playwright WebKit không hỗ trợ fake camera; kiểm camera Safari trên thiết bị thật trước pilot.')
  const teacher=await context.newPage()
  await teacher.goto('/tieu-hoc')
  await page.locator('#try-camera').click()
  await page.locator('#open-camera').click()
  await expect.poll(()=>page.evaluate(()=>Boolean(document.querySelector('.lab-area video')?.srcObject))).toBe(true)
  await teacher.locator('#teacher-tools').click()
  await teacher.getByLabel('Camera',{exact:true}).uncheck()
  await expect.poll(()=>page.evaluate(()=>document.querySelector('.lab-area video')?.srcObject===null)).toBe(true)
  await expect(page.locator('#open-camera')).toBeDisabled()
  await expect(page.locator('#open-camera')).toContainText('Camera đã tắt')
  await page.locator('#close-lab').click()
  await page.locator('#lesson-1-1').click()
  await page.locator('#lesson-listen').click()
  await expect(page.locator('#lesson-listen')).toContainText('Tạm dừng',{timeout:15000})
  await teacher.getByLabel('Audio',{exact:true}).uncheck()
  await expect(page.locator('#lesson-listen')).toBeDisabled()
  await expect(page.locator('.listen-bar')).toContainText('Giáo viên đã tắt audio')
  await expect(page.locator('#lesson-listen')).not.toContainText('Tạm dừng')
  await teacher.close()
})

test('từ chối quyền camera vẫn có phương án ảnh mẫu cục bộ',async({page,context,browserName})=>{
  await page.addInitScript(()=>{
    navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('permission denied','NotAllowedError')}
  })
  await page.reload()
  await page.locator('#try-camera').click()
  await page.locator('#open-camera').click()
  await expect(page.getByRole('alert')).toContainText('Camera chưa được cấp quyền')
  await expect(page.locator('#use-camera-fallback')).toContainText('Nhận diện ảnh mẫu trên thiết bị')
  await expect(page.locator('.camera-fallback img')).toHaveAttribute('src','/images/smart-garden.webp')
  const resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(entry=>entry.name))
  expect(resources.some(url=>/mobilenet|graph_model|tensorflow|tfjs/i.test(url))).toBe(false)
  const inferenceRequests=[]
  page.on('request',request=>inferenceRequests.push({url:request.url(),method:request.method()}))
  await page.locator('#use-camera-fallback').click()
  await expect(page.locator('.result')).toBeVisible({timeout:30000})
  const resourcesAfter=await page.evaluate(()=>performance.getEntriesByType('resource').map(entry=>entry.name))
  expect(resourcesAfter.some(url=>/mobilenet|graph_model|tensorflow|tfjs/i.test(url))).toBe(true)
  const origin=new URL(page.url()).origin
  expect(inferenceRequests.some(request=>request.method==='POST'&&!request.url.startsWith(origin))).toBe(false)
  if(browserName==='chromium'){
    await page.evaluate(()=>navigator.serviceWorker.ready)
    await page.locator('#close-lab').click()
    await context.setOffline(true)
    await page.reload()
    await page.locator('#try-camera').click()
    await page.locator('#open-camera').click()
    await page.locator('#use-camera-fallback').click()
    await expect(page.locator('.result')).toBeVisible({timeout:30000})
    await page.locator('#close-lab').click()
    await page.locator('#teacher-tools').click()
    await page.locator('#run-device-check').click()
    await expect(page.locator('.offline-resource-status li',{hasText:'MobileNet offline'})).toContainText('Sẵn sàng')
    await context.setOffline(false)
  }
})

test('không có lỗi accessibility nghiêm trọng trên trang chính và teacher mode',async({page})=>{
  await page.locator('#teacher-tools').click()
  const results=await new AxeBuilder({page}).analyze()
  expect(results.violations.filter(item=>['critical','serious'].includes(item.impact))).toEqual([])
})

test('app shell hoạt động offline sau lần tải đầu',async({page,context,browserName})=>{
  test.skip(browserName==='webkit','Playwright WebKit lỗi nội bộ khi kết hợp service worker và setOffline; kiểm Safari offline trên thiết bị thật trước pilot.')
  await page.evaluate(()=>navigator.serviceWorker.ready)
  await page.reload()
  await context.setOffline(true)
  await page.reload()
  await expect(page.locator('#hero-title')).toBeVisible()
  await expect(page.getByText('Đang học offline')).toBeVisible()
})

test('audio bài đã nghe phát lại được sau reload offline',async({page,context,browserName})=>{
  test.setTimeout(60000)
  test.skip(browserName==='webkit','Playwright WebKit lỗi nội bộ khi kết hợp service worker và setOffline; kiểm Safari offline trên thiết bị thật trước pilot.')
  await page.evaluate(()=>navigator.serviceWorker.ready)
  await page.locator('#lesson-1-1').click()
  await page.locator('#lesson-listen').click()
  await expect(page.locator('#lesson-listen')).toContainText('Tạm dừng',{timeout:15000})
  await page.locator('#lesson-listen').click()
  await page.locator('#close-lesson').click()
  await page.locator('#teacher-tools').click()
  await page.locator('#run-device-check').click()
  await expect(page.locator('.offline-resource-status li',{hasText:'Audio đã cache'})).toContainText('1 tệp')
  await page.locator('.teacher-close').click()
  await page.reload()
  await context.setOffline(true)
  await page.reload()
  await page.locator('#lesson-1-1').click()
  await page.locator('#lesson-listen').click()
  await expect(page.locator('#lesson-listen')).toContainText('Tạm dừng',{timeout:15000})
  await context.setOffline(false)
})

test('shell đạt budget thời gian và chưa tải TensorFlow',async({page})=>{
  await page.addInitScript(()=>{
    window.__largestContentfulPaint=0
    if(!('PerformanceObserver' in window))return
    try {
      const observer=new PerformanceObserver(list=>{
        const entries=list.getEntries()
        const latest=entries[entries.length-1]
        if(latest)window.__largestContentfulPaint=latest.startTime
      })
      observer.observe({type:'largest-contentful-paint',buffered:true})
    } catch {}
  })
  await page.reload()
  await page.waitForTimeout(50)
  const lcp=await page.evaluate(()=>{
    return window.__largestContentfulPaint || null
  })
  expect(lcp,'Trình duyệt phải cung cấp LCP để kiểm budget shell').not.toBeNull()
  test.info().annotations.push({type:'performance',description:`LCP shell ${Math.round(lcp)} ms`})
  console.log(`LCP shell: ${Math.round(lcp)} ms`)
  expect(lcp).toBeLessThan(2500)
  await expect(page.locator('.pwa-status')).toContainText('Audio/model: tải khi cần')
  const resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(entry=>entry.name))
  expect(resources.some(url=>/mobilenet|graph_model|tensorflow|tfjs/i.test(url))).toBe(false)
})

test('20 lần mở đóng camera đều giải phóng stream',async({page})=>{
  await page.addInitScript(()=>{
    window.__activeTracks=0
    const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices)
    navigator.mediaDevices.getUserMedia=async constraints=>{const stream=await original(constraints);for(const track of stream.getTracks()){window.__activeTracks+=1;let counted=true;const stop=track.stop.bind(track);track.stop=()=>{if(counted){window.__activeTracks-=1;counted=false}stop()}}return stream}
  })
  await page.reload()
  for(let index=0;index<20;index++){
    await page.locator('#try-camera').click()
    await page.locator('#open-camera').click()
    await page.locator('#close-lab').click()
  }
  await expect.poll(()=>page.evaluate(()=>window.__activeTracks)).toBe(0)
})
