// Explicit teaching content, not a title inserted into a shared lesson template.
const lesson = (standards,gameId,focus,example,steps,question,answer,wrong,explanation) => ({
  standards,gameId,focus,example,steps:steps.split('|'),
  quiz:{question,options:[answer,...wrong],correct:0,explanation}
})

export const primaryLessonDetails = {
  1: [
    lesson('1.A1.1 · 1.A1.2','emotion-detective','Con người thật sự cảm thấy vui, buồn, sợ hoặc ngạc nhiên. Máy có thể đoán biểu hiện nhưng không trải nghiệm cảm xúc.','Mai buồn vì mất bút. Em hỏi thăm; Bo-Bo chỉ hiện một khuôn mặt buồn.','Chỉ nét mặt của Mai và Bo-Bo|Kể lúc em từng buồn và được giúp|Chọn một lời hỏi thăm Mai','Mai đang buồn. Điều nào chỉ con người thật sự trải nghiệm?','Cảm giác buồn và cần được an ủi',['Hiện hình mặt buồn','Phát câu nói ghi sẵn'],'Hình và âm thanh thể hiện cảm xúc khác với thật sự cảm thấy buồn.'),
    lesson('1.A1.3 · 1.A1.4 · 1.A2.1 · 1.A2.MR1','emotion-detective','Biểu cảm của AI có thể là hình, giọng nói hoặc hành động do con người thiết kế. Một khuôn mặt cười không chứng minh máy đang vui. Lời chào và giọng thân thiện có thể giúp em thấy dễ chịu, dễ hợp tác hơn với máy.','Bo-Bo vừa hiện mặt cười vừa nói lời chào nhẹ nhàng. Mai thấy thoải mái hơn so với khi máy chỉ hiện dòng lệnh khó đọc; đó là cảm giác của Mai, không phải của máy.','Quan sát mặt cười và nghe lời chào|Đóng vai máy chào thân thiện rồi chào cộc lốc, nói em thấy khác nhau thế nào|Giải thích ai thiết kế biểu cảm và biểu cảm giúp người dùng ra sao','Bo-Bo nói “Tôi vui được giúp bạn”. Vì sao máy nói được?','Con người thiết kế cách máy phản hồi',['Máy vui giống hệt em','Máy có trái tim biết vui'],'Lời chào thân thiện giúp người dùng dễ tương tác, nhưng không chứng minh máy có cảm xúc thật.'),
    lesson('1.A2.2 · 1.A2.3 · 1.C1.1 · 1.C1.2','sensor-safari','Loa trợ lý xử lý lời nói và ứng dụng nhận diện hình là ví dụ công cụ AI. Không phải đồ vật chạy điện nào cũng có AI. Robot tránh vật cản có thể chỉ làm theo luật có sẵn; cần xem máy làm việc gì và bằng cách nào.','Quạt bật bằng công tắc khác loa hiểu câu hỏi để tìm bài hát.','Chọn loa trợ lý và quạt công tắc|Nói mỗi đồ vật giúp làm việc gì|Chỉ dấu hiệu nhận biết công cụ có AI','Thiết bị nào trong ví dụ đang nhận yêu cầu và xử lý ngôn ngữ?','Loa trợ lý tìm bài hát khi em nói',['Ghế gỗ','Quạt chỉ có nút bật tắt'],'Loa trợ lý dùng xử lý lời nói; bật điện đơn thuần chưa chứng minh có AI.'),
    lesson('1.C1.3 · 1.C1.MR1','sensor-safari','Camera nhận hình ảnh như “mắt” của thiết bị. Phần mềm xử lý ảnh mới đưa ra dự đoán; camera không tự hiểu mọi vật.','Che camera bằng tờ giấy thì Bo-Bo không còn thấy quả táo trước máy.','Chỉ camera trên thiết bị|So sánh ảnh táo rõ và bị che|Dự đoán điều gì giúp máy nhìn rõ hơn','Muốn Bo-Bo nhận hình quả táo, bộ phận nào nhận ảnh?','Camera',['Loa','Micro'],'Camera thu hình ảnh; micro thu âm thanh còn loa phát âm thanh.'),
    lesson('1.C1.3 · 1.C1.MR2','sound-secret','Micro thu âm thanh như “tai” của thiết bị. Giọng nói rõ và ít tiếng ồn giúp hệ thống nghe tốt hơn.','Bo-Bo nghe nhầm khi cả lớp cùng nói; khi một bạn nói rõ, tín hiệu dễ nhận hơn.','Chỉ micro và loa|So sánh nói từng người với nhiều người cùng nói|Chọn cách giúp máy nhận tiếng rõ','Bo-Bo nghe nhầm vì phòng ồn. Em nên thử gì?','Giảm tiếng ồn rồi nói rõ',['Che camera','Bật nhạc to hơn'],'Giảm tiếng ồn cải thiện âm thanh đi vào micro.'),
    lesson('1.C1.4 · 1.C1.MR1 · 1.C1.MR2','sensor-safari','AI có thể xử lý hình ảnh hoặc âm thanh, nhận lệnh đơn giản. Kết quả nhận biết vẫn có thể sai.','Máy đoán quả bóng màu cam là quả cam vì hình và màu gần giống nhau.','Chọn ảnh quả bóng và quả cam|Nêu điểm giống và khác|Hỏi người lớn kiểm tra khi máy nhầm','Máy gọi quả bóng là quả cam. Em nên nghĩ gì?','Máy có thể nhầm, cần kiểm tra lại',['Bóng đã thành quả cam','Máy luôn đúng'],'Dự đoán không làm đồ vật thay đổi; em cần quan sát thực tế.'),
    lesson('1.D1.1 · 1.D1.MR1','pattern-garden','Muốn máy học nhận một nhóm vật, con người đưa nhiều ví dụ đúng và khác nhau. Lặp một ví dụ chưa cho máy thấy đủ trường hợp.','Giỏ ảnh mèo có mèo trắng, mèo đen và mèo nằm; tất cả đều được đặt đúng tên.','Chọn ba ảnh mèo khác nhau|Loại ảnh chó khỏi giỏ mèo|Giải thích vì sao cần nhiều ví dụ','Giỏ nào giúp dạy máy về mèo tốt hơn?','Nhiều ảnh mèo khác nhau, nhãn đúng',['Một ảnh mèo chép lại nhiều lần','Ảnh chó đặt tên mèo'],'Ví dụ đúng và đa dạng giúp máy thấy nhiều trường hợp của nhóm.'),
    lesson('1.D2.1 · 1.D2.2','robot-workshop','Có máy được thiết kế làm một nhiệm vụ, có máy kết hợp nhiều nhiệm vụ. Cần xem chức năng, không chỉ nhìn hình dáng.','Máy A chỉ nhận dạng ảnh; máy B vừa nghe lời, trả lời và chạy theo lệnh.','Kể chức năng của máy A|Kể ba chức năng của máy B|Xếp hai máy vào nhóm một việc hoặc nhiều việc','Máy vừa nghe, trả lời và di chuyển thuộc nhóm nào?','Làm nhiều việc khác nhau',['Chỉ làm một việc','Không làm việc nào'],'Máy kết hợp nhiều chức năng được xếp vào nhóm nhiều việc.'),
    lesson('1.D1.1 · 1.C1.4','bobo-first-code','Con người đưa ví dụ hoặc lệnh để máy làm nhiệm vụ. Xếp lệnh robot là lập trình theo lệnh, chưa phải huấn luyện học máy.','Muốn robot đi tới cờ, em xếp phải, phải, xuống rồi xem đường chạy.','Vẽ đường tới lá cờ|Xếp lệnh và dự đoán nơi dừng|Sửa một lệnh nếu robot đi sai','Robot làm theo lệnh em xếp. Ai cần sửa khi đường đi sai?','Em kiểm tra và sửa lệnh',['Robot có cảm xúc nên tự biết','Lá cờ tự chuyển chỗ'],'Người tạo lệnh cần kiểm tra kết quả; robot không tự hiểu ý định.'),
    lesson('1.B1.1','little-data-knight','Dùng AI làm hại, trêu chọc hoặc lừa người khác là việc không nên làm, kể cả khi gọi đó là trò đùa. Khi thấy việc như vậy, em có thể từ chối và kể với người lớn đáng tin.','Một bạn muốn dùng giọng giả để làm bạn khác sợ. Em khuyên dừng.','Chọn việc giúp bạn và việc làm bạn sợ|Kể người bị ảnh hưởng cảm thấy thế nào|Nói cách từ chối tham gia việc xấu','Bạn rủ tạo giọng giả để dọa người khác. Em chọn gì?','Không tham gia và nhờ người lớn giúp',['Làm vì chỉ là đùa','Gửi cho cả lớp'],'Trò đùa gây sợ hoặc tổn thương vẫn có hại.'),
    lesson('1.B3.1 · 1.B3.2','little-data-knight','Máy thông minh nên phục vụ mục đích tốt. Con người quyết định dùng máy để giúp đỡ, không gây hại.','Cô dùng công cụ đọc truyện để cả lớp cùng nghe, không dùng giọng giả để lừa ai.','Kể một việc AI giúp lớp|Chọn người kiểm tra trước khi dùng|Vẽ ý tưởng dùng máy làm việc tốt','Việc nào dùng máy vì mục đích tốt?','Cùng cô nghe truyện bằng công cụ đọc',['Giả lời cô để lừa bạn','Tạo ảnh xấu để trêu bạn'],'Công cụ đọc hỗ trợ học tập khi được dùng đúng cách.'),
    lesson('1.B3.1 · 1.B3.2','little-data-knight','Công dân số nhí biết hỏi người lớn, giữ bí mật và cư xử tử tế. Khi chưa chắc, dừng lại là một lựa chọn tốt.','Trò chơi hỏi địa chỉ nhà. Em không nhập và hỏi bố mẹ hoặc cô giáo.','Chỉ thông tin cần giữ kín|Tập nói lời từ chối lịch sự|Chọn người lớn đáng tin để hỏi','Trò chơi lạ hỏi địa chỉ nhà. Em làm gì trước?','Dừng và hỏi người lớn đáng tin',['Nhập ngay để nhận quà','Gửi địa chỉ của bạn'],'Không nên trao thông tin riêng tư để đổi phần thưởng.')
  ],
  2: [
    lesson('2.A1.1 · 2.A1.2','safe-share-ranger','AI hữu ích cho việc tìm gợi ý, dịch hoặc hỗ trợ thiết bị; cần thận trọng khi có dữ liệu riêng tư hoặc giao hết quyết định cho máy. Trước khi dùng, em nên hỏi: việc này có cần AI không và ai sẽ kiểm tra kết quả?','Em dùng gợi ý từ vựng nhưng không gửi địa chỉ nhà để nhận lời khuyên học tập.','Kể một việc AI hỗ trợ tốt|Chọn một việc cần thận trọng|Giải thích sự khác nhau','Tình huống nào cần thận trọng trước khi dùng AI?','Công cụ đòi ảnh mặt không liên quan bài học',['Tra nghĩa từ với cô','Nghe mẫu phát âm cùng cô'],'Dữ liệu riêng tư không nên cung cấp nếu không cần và chưa được người lớn kiểm tra.'),
    lesson('2.A1.3 · 2.A1.4','sensor-river-route','Con người cần giám sát, kiểm tra và dừng hệ thống khi không an toàn. Tin công nghệ hợp lý không phải tin tuyệt đối.','Robot hút bụi tới gần vũng nước; người dùng dừng máy và xử lý chỗ ướt.','Quan sát đường robot|Chỉ nguy cơ ở vũng nước|Nói khi nào cần dừng và báo người lớn','Robot sắp tới vũng nước. Ai cần kiểm soát?','Người dùng quan sát và dừng máy',['Chờ máy luôn tự xử lý','Không ai cần quan sát'],'Giám sát giúp ngăn rủi ro trước khi xảy ra.'),
    lesson('2.A2.1 · 2.A2.2','sensor-river-route','AI có thể hỗ trợ nhiều thành viên trong gia đình: loa nhận lệnh, robot dọn nhà, công cụ đọc chữ. Trẻ em dùng dưới hướng dẫn.','Ông nghe sách bằng giọng đọc; bố mẹ dùng robot dọn sàn; em học phát âm cùng mẹ.','Ghép thiết bị với người được giúp|Nêu công dụng của từng thiết bị|Chọn việc em cần người lớn hướng dẫn','Công cụ đọc chữ thành tiếng trong nhà có thể giúp ai?','Ông khó đọc chữ nhỏ',['Chỉ người lập trình','Chỉ chiếc bàn'],'AI có thể hỗ trợ nhu cầu khác nhau của các thành viên.'),
    lesson('2.C1.1 · 2.C1.MR1','data-garden','Dữ liệu là ví dụ như hình ảnh, âm thanh được dùng để dạy AI. Tên nhóm cho biết ví dụ thuộc loại nào. Em và máy đều có thể học qua ví dụ, nhưng em còn hỏi, trải nghiệm và hiểu lời giải thích; máy học bằng tính toán từ dữ liệu theo cách được thiết kế. Máy xem ảnh quả không có nghĩa máy đã nếm quả.','Em nhìn, ngửi và hỏi cô về chuối; máy nhận các ảnh chuối xanh, chuối chín có nhãn để tìm điểm chung trong dữ liệu.','Chọn ví dụ hình và âm thanh dùng dạy máy|So sánh em học về chuối thế nào và máy nhận dữ liệu gì|Ghép ảnh với nhãn rồi nêu một điểm giống, một điểm khác giữa em và máy','Trong hoạt động dạy nhận chuối, dữ liệu là gì?','Các ảnh chuối dùng làm ví dụ',['Tên người chiến thắng','Màu vỏ máy tính'],'Dữ liệu là thông tin được dùng để máy học nhiệm vụ. Học từ ảnh không đồng nghĩa có trải nghiệm và cách hiểu như con người.'),
    lesson('2.C3.1 · 2.C3.2','data-garden','Phân loại là xếp vật vào nhóm theo tiêu chí. AI có thể phân loại sai nếu ví dụ thiếu hoặc không rõ.','Bóng và cam đều tròn nhưng chỉ cam thuộc nhóm trái cây.','Nêu tiêu chí trái cây hoặc không|Phân loại cam, bóng và chuối|Giải thích vì sao không chỉ nhìn hình tròn','Theo tiêu chí trái cây, quả bóng vào nhóm nào?','Không phải trái cây',['Trái cây vì hình tròn','Cả hai nhóm'],'Tiêu chí nhóm quan trọng hơn một đặc điểm bề ngoài giống nhau.'),
    lesson('2.A3.1 · 2.A3.MR1','garden-coder','Một số hệ thống có thể ghi nhận phản hồi, lựa chọn để cải thiện gợi ý. Không phải mỗi tin nhắn đều lập tức huấn luyện lại máy.','Em báo gợi ý không phù hợp; hệ thống có thể dùng phản hồi theo cách nhà thiết kế quy định.','Đọc một gợi ý đúng và một gợi ý sai|Chọn phản hồi lịch sự, chính xác|Nói vì sao không đưa thông tin giả','Phản hồi nào giúp ích hơn khi AI gợi ý sai?','Nêu rõ chỗ sai một cách lịch sự',['Cố tình xác nhận điều sai','Gửi lời xúc phạm'],'Phản hồi đúng cung cấp tín hiệu hữu ích; sai lệch có thể làm chất lượng kém đi.'),
    lesson('2.D1.1 · 2.D1.2','garden-coder','Ý tưởng máy thông minh bắt đầu từ một vấn đề gần gũi. Cần nói máy giúp ai, nhận dữ liệu gì và làm việc gì.','Lớp hay quên tưới cây nên nghĩ ra công cụ nhắc khi đất khô.','Chọn vấn đề ở góc cây|Vẽ máy nhắc tưới|Nói máy cần biết đất khô hay ẩm','Trước khi vẽ máy thông minh, nhóm nên làm gì?','Nêu vấn đề cần giúp giải quyết',['Chọn thật nhiều đèn','Đặt tên người chiến thắng'],'Mục đích rõ giúp chọn chức năng phù hợp.'),
    lesson('2.D2.1 · 2.D2.2','data-garden','Dữ liệu rõ và đúng giúp máy học phù hợp. Ảnh sai nhãn hoặc bị che làm máy nhận biết kém.','Một ảnh táo bị đặt nhãn chuối khiến giỏ ví dụ không đáng tin.','Tìm thẻ sai nhãn|Đặt lại nhãn đúng|So sánh bộ trước và sau sửa','Ảnh táo mang nhãn chuối nên được xử lý thế nào?','Sửa nhãn thành táo',['Giữ vì đủ số lượng','Đổi mọi nhãn thành chuối'],'Dữ liệu cần đúng nghĩa, không chỉ đủ số mẫu.'),
    lesson('2.D1.MR1 · 2.D2.MR1 · 2.C3.MR1','data-garden','Khi thử dạy phân loại, cần chuẩn bị ví dụ, đặt nhãn và thử một mẫu mới. Kết quả sai là cơ hội xem lại dữ liệu.','Nhóm dùng ảnh táo đỏ và xanh để dạy, rồi thử bằng ảnh táo khác.','Thu thập ví dụ hai nhóm|Kiểm tra nhãn cùng bạn|Thử ảnh mới và ghi máy đoán đúng hay sai','Nên thử máy bằng ảnh nào để có thêm thông tin?','Một ảnh mới chưa dùng để dạy',['Chỉ ảnh đã xem nhiều lần','Một màn hình trống'],'Mẫu mới cho thấy máy xử lý trường hợp khác ra sao.'),
    lesson('2.B3.1 · 2.B3.2 · 2.B3.MR1 · 2.B3.MR2','trusted-source-match','Có đồ của em, đồ của bạn và đồ dùng chung: bút của em khác bút em mượn của Lan; sách thư viện không trở thành của em khi em mang về đọc. Tranh và truyện cũng cần tôn trọng người tạo. Với sản phẩm có AI hỗ trợ, không tự nhận phần của người khác là của mình; nhờ người lớn kiểm tra quyền sử dụng.','Lan vẽ tranh, Minh mượn bút của Lan và cùng cô làm một tấm thiệp có AI hỗ trợ. Minh không được tự lấy tranh của Lan làm mẫu chỉ vì máy có thể sao chép.','Chia bút của em, bút mượn của Lan và sách thư viện thành của mình, của người khác, dùng chung|Đóng vai xin dùng tranh Lan làm mẫu, thực hành cả khi Lan đồng ý và từ chối|Nói phần em tự làm trong thiệp, phần AI hỗ trợ và việc cần hỏi người lớn trước khi dùng','Minh muốn dùng tranh của Lan. Minh nên làm gì?','Xin phép Lan và tôn trọng câu trả lời',['Xóa tên Lan rồi dùng','Lấy vì tranh ở trong lớp'],'Thấy, mượn hoặc sao chép được một sản phẩm không có nghĩa được tự ý sử dụng hay nhận là của mình.'),
    lesson('2.B1.1 · 2.B1.MR1 · 2.B1.MR2','data-garden','Thiên kiến là khi AI có thể đối xử không công bằng với một số nhóm người. Ví dụ, công cụ nghe hiểu tốt một giọng nói nhưng thường nghe sai giọng khác khiến một số bạn khó sử dụng hơn. Dữ liệu ít đa dạng có thể góp phần gây lỗi; không được đổ lỗi cho các bạn đó.','Trong tình huống giả định, máy nghe đúng 4 trong 5 câu của nhóm giọng A nhưng chỉ 1 trong 5 câu của nhóm giọng B. Cả hai nhóm đều nói đúng câu; bộ ví dụ dạy máy có rất ít giọng B.','Chỉ nhóm bạn bị máy nghe sai nhiều hơn|Giải thích vì sao không nên loại các bạn ấy khỏi hoạt động|Đề xuất bổ sung ví dụ giọng còn thiếu với sự đồng ý và hỗ trợ của người lớn, rồi thử lại','Máy hay nghe sai giọng của một nhóm bạn. Cách xử lý nào công bằng hơn?','Giúp các bạn tham gia, bổ sung ví dụ phù hợp rồi kiểm tra lại',['Không cho nhóm đó dùng máy','Yêu cầu các bạn nhận lỗi vì máy nghe sai'],'Cần xem tác động lên con người, không chỉ tổng số câu đúng. Thêm dữ liệu có thể giúp nhưng chưa bảo đảm hết thiên kiến. Trò trái cây chỉ minh họa dữ liệu thiếu; quả xanh không phải một nhóm người.'),
    lesson('2.A1.4 · 2.B3.2','safe-share-ranger','Dùng AI có trách nhiệm là kiểm tra kết quả, tôn trọng sản phẩm và nhờ người lớn khi gặp điều lạ. Không đổ mọi lỗi cho máy.','AI tạo lời nhắn có tên bạn sai; em sửa trước khi gửi và nói mình có dùng công cụ.','Tìm lỗi trong lời nhắn|Sửa tên và kiểm tra với người nhận|Nêu người chịu trách nhiệm khi gửi','Ai cần kiểm tra lời nhắn AI trước khi gửi?','Người định gửi lời nhắn',['Chỉ người nhận','Không ai vì AI viết'],'Người sử dụng kết quả vẫn chịu trách nhiệm cho lựa chọn của mình.')
  ],
  3: [
    lesson('3.A1.1 · 3.A1.2 · 3.A2.1 · 3.A2.2 · 3.A2.3','grade-3-ai-study','Trợ lý học tập có thể gợi ý từng bước; ứng dụng ngôn ngữ có thể cho nghe mẫu và phản hồi phát âm. Ở trường, AI còn có thể nhận dạng chữ viết hoặc gợi ý bài luyện cho giáo viên. Cá nhân hóa là điều chỉnh bài theo nhu cầu: bạn cần luyện thêm nhận bài cơ bản, bạn đã hiểu nhận bài vận dụng. Giáo viên kiểm tra việc điều chỉnh; không để máy tự gắn nhãn năng lực cố định cho học sinh. Bảng có màn hình chưa chắc có AI.','Lan cần luyện phát âm, Minh cần bài đọc khó hơn. Cô chọn ứng dụng phù hợp, cho hai bạn nhiệm vụ khác nhau và dùng trò tương tác để tăng hứng thú. Công cụ nhận chữ giúp cô chuyển bài viết thành văn bản nhưng cô vẫn kiểm tra lỗi.','Ghép nhu cầu của Lan, Minh và cô với công cụ hỗ trợ phù hợp|Dưới hướng dẫn của cô, chọn từ cần luyện, nghe mẫu rồi tự đọc; xin gợi ý khi chưa hiểu|Giải thích vì sao hai bạn nhận bài khác nhau và nêu việc cô cần kiểm tra','Lan cần luyện phát âm, Minh đã đọc tốt. Cách dùng AI nào phù hợp hơn?','Cô chọn bài vừa sức cho từng bạn, hai bạn tự luyện rồi cô kiểm tra',['Cho AI làm hết bài của cả hai bạn','Buộc hai bạn học cùng bài khó dù chưa hiểu'],'AI hỗ trợ cả học sinh và giáo viên. Cá nhân hóa giúp bài phù hợp nhu cầu, còn học sinh vẫn tự thực hành và giáo viên giữ vai trò kiểm tra.'),
    lesson('3.A1.3 · 3.A1.MR2','grade-3-ai-study','Dùng AI làm thay toàn bộ khiến em ít luyện tư duy. Tự làm trước, tham khảo có chọn lọc và giải thích lại giúp giữ sự tự chủ.','Hai bạn cùng có đáp án nhưng chỉ bạn tự làm giải thích được cách tìm kết quả.','Tự làm một câu ngắn|So sánh với gợi ý AI|Giải thích bằng lời của mình','Dấu hiệu nào cho thấy em không phụ thuộc hoàn toàn vào AI?','Tự giải được bài tương tự và nêu cách làm',['Chép nhanh hơn','Nhớ nút gửi câu hỏi'],'Năng lực thể hiện qua việc tự làm, không chỉ nhận đáp án.'),
    lesson('3.A3.1 · 3.A3.2 · 3.A1.4 · 3.A1.5','evidence-detective','AI có thể dịch sai, nhầm hình hoặc trả lời thiếu căn cứ. Cần đối chiếu nguồn liên quan và hỏi người phù hợp.','AI nói trường nghỉ thứ hai, nhưng thông báo nhà trường ghi vẫn học bình thường.','Xác định phát biểu cần kiểm tra|Đọc thông báo chính thức và xem ngày|Kết luận dựa trên nội dung nguồn','AI báo nghỉ học trái thông báo mới của trường. Em dựa vào đâu?','Thông báo mới, chính thức của trường',['Câu AI viết tự tin hơn','Tin nhắn không ghi nguồn'],'Nguồn có thẩm quyền và đúng thời điểm phù hợp cho lịch của trường.'),
    lesson('3.C4.1','grade-3-feature-sort','Dữ liệu có thể là số, chữ, ảnh hoặc âm thanh. Dữ liệu cần gắn với câu hỏi cần giải quyết.','Để biết cây cần nước, nhóm ghi độ ẩm đất theo ngày thay vì màu áo của người tưới.','Nêu câu hỏi về cây|Chọn ba dữ liệu liên quan|Loại thông tin không giúp trả lời','Dữ liệu nào liên quan trực tiếp đến đất đang khô hay ẩm?','Số đo độ ẩm đất',['Màu áo của em','Tên bài hát yêu thích'],'Dữ liệu hữu ích phải phù hợp với câu hỏi đang xét.'),
    lesson('3.C4.MR1','grade-3-feature-sort','Đặc trưng là thuộc tính như chiều dài, màu và hình; nhãn là nhóm cần nhận biết. Hai khái niệm không giống nhau.','Thẻ ghi dài 8 cm, xanh, nhóm lá dài: hai phần đầu là đặc trưng, phần cuối là nhãn.','Đọc thẻ mẫu lá|Tách cột đặc trưng và nhãn|Tạo thẻ cho một lá khác','Trong thẻ “xanh, 8 cm, nhóm lá dài”, đâu là nhãn?','Nhóm lá dài',['Màu xanh','8 cm'],'Nhãn là nhóm kết quả; màu và chiều dài mô tả mẫu.'),
    lesson('3.C5.1 · 3.C5.MR1','grade-3-if-then','Luật nếu–thì nối điều kiện với hành động. Cần thử phản ví dụ để phát hiện luật quá đơn giản.','Luật có bốn chân thì là mèo nhầm con chó; cần điều kiện phân biệt phù hợp hơn.','Viết một luật phân loại|Thử với mèo và chó|Nêu điểm cần sửa trong luật','Con chó chứng minh điều gì về luật “bốn chân thì là mèo”?','Luật chưa đủ để phân biệt',['Mọi chó đều là mèo','Không thể viết bất kỳ luật nào'],'Một phản ví dụ đủ cho thấy luật hiện tại có trường hợp sai.'),
    lesson('3.D1.1 · 3.C5.2 · 3.C5.3 · 3.C5.4','grade-3-train-order','Học máy học các mẫu từ dữ liệu thay vì con người viết sẵn mọi luật. Muốn dạy nhận rau, ta thu thập ảnh, ghi đúng tên nhóm, cho máy học rồi thử ảnh mới. Phân loại cho kết quả là tên nhóm; dự đoán một giá trị cho kết quả là một số như lượng mưa. Nói rộng ra, phân loại cũng là một cách dự đoán: máy dự đoán nhãn, không phải biết chắc.','Nông trại dùng ảnh để xếp rau vào nhóm cải hoặc xà lách. Một mô hình khác dùng số đo thời tiết các ngày trước để ước lượng ngày mai mưa 12 mm. Kết quả “có mưa/không mưa” lại là hai nhóm, không phải lượng mưa.','Ghép đầu ra cải/xà lách, có mưa/không mưa và 12 mm với tên nhóm hoặc giá trị số|Xếp bước thu thập ví dụ, gắn nhãn, cho học rồi thử mẫu mới|Nêu dữ liệu cho từng bài toán và giải thích vì sao đầu ra vẫn có thể sai','Đầu ra nào là dự đoán giá trị số, không phải phân loại?','Ước lượng ngày mai mưa 12 mm',['Xếp rau vào nhóm cải','Xếp ngày mai vào nhóm có mưa'],'Cần nhìn dạng đầu ra, không chỉ thấy từ “ngày mai”. Tên nhóm là phân loại; lượng mưa là giá trị số. Cả hai đều có thể sai và cần kiểm tra.'),
    lesson('3.D2.1 · 3.D2.2 · 3.D2.MR1','grade-3-clean-data','Dữ liệu học cần đúng nhãn, đủ rõ và phù hợp. Cần tìm thẻ thiếu, sai sự thật hoặc không liên quan.','Một giỏ táo có ảnh xe, ảnh táo nhòe và ảnh táo rõ; không phải thẻ nào cũng dùng được.','Kiểm tra từng thẻ trong giỏ|Giữ thẻ rõ, sửa nhãn hoặc loại thẻ không dùng được|Ghi lý do xử lý mỗi thẻ','Ảnh không nhìn ra vật nên được xử lý thế nào?','Chụp lại hoặc loại khỏi bộ học',['Đoán nhãn tùy ý','Giữ vì cần nhiều ảnh'],'Gán nhãn phỏng đoán cho ảnh không rõ có thể thêm sai lệch.'),
    lesson('3.D2.3','grade-3-clean-data','Máy có thể học sai từ nhãn sai hoặc ví dụ thiếu. Muốn tìm nguyên nhân, cần xem dữ liệu và thử lại sau khi sửa.','Máy gọi chuối là táo vì nhiều ảnh chuối bị gắn nhãn táo.','Tìm nhãn của ảnh chuối|Sửa bộ dữ liệu|Thử lại bằng ảnh chuối mới','Máy nhầm do nhiều nhãn sai. Bước phù hợp nhất?','Sửa nhãn, học lại rồi kiểm thử',['Chỉ đổi màu giao diện','Xóa mọi ca máy đoán sai'],'Sửa nguyên nhân trong dữ liệu cần đi kèm đánh giá kết quả mới.'),
    lesson('3.B2.1','evidence-detective','Văn bản, ảnh và âm thanh do AI tạo có thể giống thật mà không mô tả sự kiện thật. Cần kiểm chứng nội dung.','Một ảnh con voi trong sân trường không có nguồn hoặc người xác nhận.','Nêu điều ảnh muốn em tin|Tìm nguồn gốc và bằng chứng độc lập|Quyết định có nên chia sẻ chưa','Ảnh AI rất giống thật có đủ chứng minh sự kiện không?','Chưa, cần bằng chứng về sự kiện',['Có, nếu nhiều màu','Có, nếu nhiều người thích'],'Vẻ ngoài chân thực không phải chứng cứ sự kiện đã xảy ra.'),
    lesson('3.B3.1 · 3.B3.MR1','grade-3-kind-ai','Không dùng AI để lừa đảo, bắt nạt hoặc gây hại. Dữ liệu đúng và đa dạng cũng là một phần sử dụng có trách nhiệm.','Nhóm dùng AI làm tranh nhắc bỏ rác, kiểm tra nội dung và tránh chế giễu người nào.','Nêu mục đích của tấm tranh|Kiểm tra ai có thể bị ảnh hưởng|Sửa thông điệp để tử tế và chính xác','Thông điệp nào phù hợp cho tranh AI của lớp?','Nhắc giữ sạch sân trường, không chế giễu ai',['Bịa lỗi của một bạn','Giả thông báo để dọa người khác'],'Mục đích tốt không được đi kèm cách làm gây hại.'),
    lesson('3.B3.1','grade-3-kind-ai','Tôn trọng tác giả và điều kiện sử dụng khi dùng ảnh, nhạc, truyện làm nguyên liệu cho AI. Ghi nguồn không tự thay thế việc xin phép khi cần.','Em muốn dùng nhạc của người khác trong video AI; cần xem giấy phép trước khi đăng.','Tìm tên tác giả và điều kiện sử dụng|Chọn xin phép hoặc đổi nguồn được phép|Ghi nguồn và nói rõ phần có AI hỗ trợ','Chỉ ghi tên tác giả đã luôn đủ để dùng nhạc chưa?','Chưa, còn cần quyền hoặc điều kiện cho phép',['Luôn đủ','Không cần xem quyền sử dụng'],'Ghi nguồn và có quyền sử dụng là hai yêu cầu khác nhau.')
  ],
  4: [
    lesson('4.A1.1','grade-4-ai-jobs','AI hỗ trợ nông nghiệp, giao thông và nhiều công việc bằng cách xử lý dữ liệu. Người dùng cần hiểu nhiệm vụ và kiểm tra kết quả. Mỗi ngành dùng loại dữ liệu khác nhau, nên công cụ tốt ở nơi này chưa chắc phù hợp ở nơi khác.','Công cụ xem ảnh lúa để cảnh báo dấu hiệu bất thường, người trồng kiểm tra lại ngoài ruộng.','Chọn một công việc ở địa phương|Nêu dữ liệu AI cần|Nêu người kiểm tra kết quả','Trong ví dụ ruộng lúa, AI hỗ trợ công việc nào?','Tìm dấu hiệu bất thường trong ảnh lá',['Chịu trách nhiệm thay mọi người','Tự hiểu mọi ruộng không cần ảnh'],'AI phân tích dữ liệu trong nhiệm vụ cụ thể, vẫn cần kiểm tra thực tế.'),
    lesson('4.A1.2 · 4.A1.MR1','grade-4-human-control','AI có thể gợi ý nhanh nhưng không thay việc hiểu bài, cân nhắc hoàn cảnh và sáng tạo của con người. Em giữ vai trò quyết định: đọc gợi ý, đối chiếu với điều đã học rồi chọn cách làm an toàn.','AI đưa một cách làm thí nghiệm; em và cô kiểm tra vật liệu có an toàn và phù hợp không.','Đọc gợi ý thí nghiệm|Chỉ điều cần người xem lại|Viết cách điều chỉnh an toàn','Vì sao cần xem lại gợi ý thí nghiệm của AI?','Để kiểm tra an toàn và hiểu cách làm',['Vì mọi gợi ý đều sai','Vì chỉ cần chép chậm hơn'],'Kiểm tra không phải phủ nhận mọi kết quả, mà dùng chúng có hiểu biết.'),
    lesson('4.A2.1 · 4.A2.2','grade-4-ai-jobs','AI hướng tới giải quyết nhu cầu và giúp đời sống tốt hơn. Cần xem cả người lao động, người yếu thế và người khó tiếp cận công nghệ. Một giải pháp chỉ thật sự tốt khi người cần nó dùng được, không chỉ khi nó chạy nhanh.','Công cụ đọc biển báo thành tiếng hỗ trợ người khó nhìn chữ.','Chọn người gặp khó khăn|Mô tả AI có thể giúp phần nào|Nêu một giới hạn cần người hỗ trợ','Tiêu chí nào quan trọng khi chọn giải pháp hỗ trợ người khó đọc?','Người dùng hiểu và sử dụng được',['Chỉ có hình thật đẹp','Có nhiều nút nhất'],'Lợi ích cần được đánh giá từ người được phục vụ.'),
    lesson('4.C2.1 · 4.C2.MR1','grade-4-ai-jobs','Ứng dụng AI quen thuộc gồm nhận dạng chữ, dịch và gợi ý học tập. Cần biết đầu vào, đầu ra và giới hạn của mỗi ứng dụng. Biết giới hạn giúp em chọn đúng lúc nên dùng và lúc nên tự kiểm tra lại.','Ảnh chữ viết tay được chuyển thành văn bản nhưng có một từ bị nhận sai.','Chọn ảnh chữ rõ|Đối chiếu văn bản máy nhận với bản gốc|Sửa lỗi và giải thích nguyên nhân có thể','Sau khi AI nhận dạng chữ viết tay, cần làm gì?','So văn bản với bản gốc và sửa lỗi',['Xóa bản gốc ngay','Tin mọi chữ đã nhận'],'Nhận dạng chữ vẫn có thể sai do nét viết hoặc chất lượng ảnh.'),
    lesson('4.C5.MR1 · 4.C5.MR2','shield-coder','Học máy có giám sát dùng mẫu có nhãn. Quy trình gồm đặt nhóm, đưa mẫu, cho học và thử ảnh mới. Nhãn sai hoặc thiếu một nhóm sẽ làm mô hình học lệch, dù số lượng mẫu vẫn nhiều.','Nhóm huấn luyện phân biệt hai loại lá rồi đổi một nhãn để quan sát ảnh hưởng.','Đặt nhãn và huấn luyện lần A|Đổi một nhãn, huấn luyện lần B|So sánh cùng các mẫu kiểm thử','Để so hai lần huấn luyện, yếu tố nào nên giữ nguyên?','Bộ mẫu kiểm thử',['Mọi nhãn sai','Kết quả mong muốn bất kể dữ liệu'],'Cùng phép thử giúp nhận ra tác động của thay đổi dữ liệu.'),
    lesson('4.C2.1 · 4.C2.MR1','grade-4-model-test','Hình và tiếng là hai dạng đầu vào khác nhau. Ánh sáng, góc chụp và tiếng ồn ảnh hưởng kết quả nhận biết. Muốn biết yếu tố nào gây sai, mỗi lần thử em chỉ đổi một yếu tố.','Ứng dụng nghe nhầm ở sân ồn nhưng tốt hơn khi nói rõ trong phòng yên.','Chọn đầu vào hình hoặc tiếng|Nêu nguồn gây nhiễu tương ứng|Đề xuất một phép thử chỉ đổi độ nhiễu','Muốn kiểm tra tiếng ồn có làm máy nghe sai, nên?','Giữ câu nói, đổi môi trường ồn và yên',['Đổi câu, người nói và máy cùng lúc','Chỉ thay hình nền'],'Giữ các yếu tố khác giúp xác định tác động của tiếng ồn.'),
    lesson('4.D1.1 · 4.D1.MR1','grade-4-design-workshop','Một ý tưởng AI cần vấn đề, người dùng và kết quả mong muốn. Ưu tiên nhu cầu thật tại trường hoặc địa phương. Nêu rõ ai dùng và dùng để làm gì giúp nhóm chọn được dữ liệu và cách đánh giá phù hợp.','Lớp muốn hỗ trợ phân loại rác vì giấy và nhựa hay bị bỏ chung.','Hỏi người trực nhật về khó khăn|Vẽ đầu vào và đầu ra của giải pháp|Nêu cách biết ý tưởng có giúp ích','Mục tiêu nào rõ nhất cho ý tưởng phân loại rác?','Giúp phân biệt giấy và nhựa ở góc lớp',['Làm máy thông minh nhất thế giới','Có thật nhiều màu đèn'],'Mục tiêu cụ thể giúp thiết kế và kiểm tra được kết quả.'),
    lesson('4.C5.MR1 · 4.C5.MR2','grade-4-data-collector','Thu thập mẫu cần đúng nhóm, đa dạng và không kèm dữ liệu riêng tư không cần thiết. Số lượng lớn không đủ nếu toàn mẫu giống nhau. Hãy để riêng vài mẫu chưa dùng để học, dành cho lúc kiểm tra.','10 ảnh của cùng lá trên nền trắng không thay được nhiều lá và nhiều góc chụp.','Chọn các lá khác nhau mỗi nhóm|Chụp không có mặt hoặc thẻ tên|Kiểm tra nhãn và dành mẫu mới để thử','Bộ nào đa dạng hơn cho bài nhận lá?','Nhiều lá, nhiều góc, nhãn đúng',['Một ảnh nhân bản 100 lần','Nhiều ảnh không có lá'],'Đa dạng mô tả các trường hợp khác nhau, không chỉ số tệp.'),
    lesson('4.D2.1','grade-4-model-test','Cải tiến cần đánh giá, tìm lỗi và thay đổi có lý do. Ghi kết quả trước/sau để biết thay đổi có hiệu quả không. Nếu đổi nhiều thứ cùng lúc, nhóm sẽ không biết điều nào tạo ra kết quả tốt hơn.','Lần A sai ảnh tối; nhóm thêm ảnh tối vào tập học và thử lại trên bộ độc lập.','Ghi loại lỗi lần A|Thay một yếu tố phù hợp|So kết quả lần B và nêu giới hạn','Chứng cứ nào tốt nhất cho một lần cải tiến?','Kết quả trước/sau trên cùng bộ thử và ghi thay đổi',['Lời nhận xét máy đẹp hơn','Chỉ kết quả tốt nhất được chọn'],'Minh chứng cần đủ điều kiện so sánh, không chọn lọc kết quả đẹp.'),
    lesson('4.B2.1 · 4.B2.2','privacy-shield','Dữ liệu riêng tư gồm mật khẩu, địa chỉ, số điện thoại, ảnh có nhận dạng. Bị lộ có thể dẫn tới giả mạo hoặc làm phiền. Trước khi gửi, em nên nghĩ ai có thể xem được và thông tin đó sẽ được giữ lại bao lâu.','Ảnh vé có tên và mã số; dù không có mặt, vẫn có thông tin cần giữ kín.','Đánh dấu thông tin riêng trên vé giả định|Nêu rủi ro khi đăng nguyên ảnh|Chọn cách chia sẻ ít thông tin hơn','Ảnh không có mặt nhưng có tên và mã vé có riêng tư không?','Có, tên và mã vẫn cần được bảo vệ',['Không vì thiếu mặt','Không vì là ảnh giấy'],'Dữ liệu riêng tư không chỉ là khuôn mặt.'),
    lesson('4.A3.1 · 4.A3.MR1','grade-4-human-control','Con người có quyền chọn, từ chối hoặc dừng AI theo mục đích, nhu cầu và an toàn. Sự phổ biến không bảo đảm phù hợp. Nếu công cụ xin dữ liệu không liên quan tới việc cần làm, đó là dấu hiệu nên hỏi người lớn.','Công cụ xin vị trí chính xác để chọn màu tranh; em từ chối yêu cầu không liên quan.','Xác định mục đích dùng công cụ|So dữ liệu xin với mục đích|Chọn dùng, từ chối hoặc hỏi thêm','Công cụ xin vị trí để chọn màu tranh. Quyết định phù hợp?','Từ chối và hỏi lý do cần dữ liệu',['Cho phép vì nhiều bạn dùng','Gửi vị trí của người khác'],'Quyền từ chối giúp kiểm soát rủi ro không cần thiết.'),
    lesson('4.B2.MR1','grade-4-privacy-rescue','Khi lộ thông tin, cần bình tĩnh, ngừng chia sẻ và báo người lớn đáng tin. Tùy dữ liệu mà có cách xử lý phù hợp. Xóa tin nhắn không bảo đảm dữ liệu đã biến mất, nên vẫn cần xử lý ở tài khoản.','Nếu lộ mật khẩu, nhờ người lớn đổi qua trang chính thức, không gửi tiếp mã xác nhận.','Đọc tình huống lộ mật khẩu giả định|Xếp việc báo người lớn và đổi mật khẩu|Nêu việc không nên làm tiếp','Lỡ nhập mật khẩu vào công cụ lạ, nên ưu tiên gì?','Báo người lớn và đổi mật khẩu an toàn',['Chỉ xóa dòng chữ đã nhập','Gửi thêm mã đăng nhập'],'Thông tin có thể đã được ghi nhận; cần bảo vệ tài khoản, không chỉ xóa trên màn hình.')
  ],
  5: [
    lesson('5.A1.1 · 5.A1.2 · 5.A1.MR1','grade-5-human-responsibility','AI làm tốt một số việc lặp lại hoặc xử lý nhiều dữ liệu. Người tạo, vận hành và sử dụng vẫn cần kiểm tra và chịu trách nhiệm. Trách nhiệm được chia theo vai: ai vận hành, ai kiểm thử và ai phê duyệt trước khi dùng tiếp.','Máy kiểm tra sản phẩm bỏ sót lỗi; người phụ trách rà soát và sửa quy trình.','Xác định phần việc của máy|Nêu người kiểm tra đầu ra|Đề xuất cách báo lỗi và dừng','AI bỏ sót lỗi, điều nào đúng về trách nhiệm?','Con người liên quan phải kiểm tra và khắc phục',['Chỉ máy chịu trách nhiệm','Không ai cần xử lý'],'Công cụ không thay thế trách nhiệm của người thiết kế và sử dụng.'),
    lesson('5.A2.1 · 5.A2.MR1','grade-5-human-responsibility','Mục đích AI là hỗ trợ con người. Con người cân nhắc hoàn cảnh, cảm xúc và trách nhiệm khi dùng gợi ý. Gợi ý của máy dựa trên mẫu chung, còn hoàn cảnh riêng của từng người thì chỉ con người nắm được.','AI viết lời an ủi nhưng em sửa theo điều bạn thật sự đang trải qua.','So gợi ý chung với hoàn cảnh của bạn|Nêu điểm cần người điều chỉnh|Viết lời hỗ trợ bằng giọng của em','AI soạn lời an ủi. Vì sao em vẫn nên điều chỉnh?','Vì em cần hiểu hoàn cảnh và chịu trách nhiệm lời nói',['Vì máy không viết được chữ','Vì mọi lời AI đều sai'],'Câu chữ hợp lý chưa đủ thay sự quan tâm và lựa chọn của người thật.'),
    lesson('5.A3.1 · 5.A3.2 · 5.A2.2 · 5.A2.3','grade-5-community-ai','Mọi lứa tuổi cần hiểu cách dùng AI an toàn, phù hợp nhu cầu. Công nghệ nên phục vụ lợi ích chung, không chỉ một nhóm thuận lợi. Khi thiết kế, cần hỏi cả người ít quen công nghệ để không bỏ sót nhu cầu của họ.','Một trợ lý đọc hướng dẫn cần chữ lớn cho ông và cách dùng đơn giản cho em nhỏ.','Chọn hai nhóm người dùng|Nêu nhu cầu khác nhau|Đề xuất cách hỗ trợ cả hai','Thiết kế AI cho cả trẻ nhỏ và người cao tuổi nên?','Điều chỉnh cách hướng dẫn theo nhu cầu',['Buộc mọi người dùng một cách khó','Chỉ phục vụ người thao tác nhanh'],'Thiết kế lấy con người làm trung tâm xem sự khác nhau giữa người dùng.'),
    lesson('5.C5.1 · 5.C5.MR1','grade-5-rule-tree','Cấu trúc nếu–thì nối điều kiện và hành động. Cây quyết định có nhiều nhánh; cần xử lý nhánh không biết và luật mâu thuẫn. Mỗi nhánh nên dựa trên một điều kiện kiểm tra được, tránh điều kiện mơ hồ.','Vật trong suốt có thể là nhựa hoặc thủy tinh nên cây phân loại cần hỏi thêm vật liệu.','Vẽ hai nhánh giấy và nhựa|Thử một vật không khớp|Thêm nhánh hỏi người kiểm tra','Cây luật gặp vật không khớp nhánh nào nên làm gì?','Chuyển người kiểm tra hoặc nhánh chưa biết',['Đoán bất kỳ và giấu','Luôn coi là nhựa'],'Nhánh chưa biết giúp tránh quyết định sai với trường hợp ngoài luật.'),
    lesson('5.C5.2 · 5.C5.MR2','grade-5-learning-leaves','Công cụ học máy trực quan cho phép gắn nhãn, huấn luyện và thử mô hình. Cần tự thực hiện các bước, không chỉ xem kết quả mẫu. Quan sát lúc huấn luyện giúp em biết dữ liệu đã đủ hay còn nhóm bị thiếu mẫu.','Em tạo mô hình lá từ dữ liệu mẫu có nhãn rồi kiểm tra các lá chưa dùng để học.','Chuẩn bị hai nhóm lá có nhãn|Huấn luyện và quan sát trạng thái|Thử mẫu mới, lưu kết quả','Sau khi đưa mẫu đúng nhãn vào công cụ, bước tiếp là gì?','Cho mô hình học rồi thử bằng mẫu mới',['Công bố máy luôn đúng','Xóa bộ kiểm thử'],'Huấn luyện và kiểm thử là hai bước cần thiết để biết mô hình làm được gì.'),
    lesson('5.C5.MR3','grade-5-new-data','Kiểm tra cần mẫu chưa dùng để huấn luyện, ghi nhãn thật và dự đoán. Điểm tốt trên tập học không đủ chứng minh khả năng xử lý mẫu mới. Vì vậy kết quả cần báo kèm số mẫu thử và những trường hợp mô hình còn nhầm.','Mô hình đúng 10/10 mẫu học nhưng chỉ 6/10 mẫu mới; hai kết quả nói những điều khác nhau.','Tách tập học và tập thử|Đếm đúng sai trên mẫu mới|Nêu trường hợp mô hình còn nhầm','Kết quả nào hữu ích hơn để đánh giá mẫu chưa thấy?','6/10 trên tập mới, kèm loại lỗi',['10/10 trên ảnh đã học','Số lần bấm huấn luyện'],'Tập mới đo khả năng ngoài dữ liệu đã học, cần đọc cả ca sai.'),
    lesson('5.D1.1 · 5.D1.MR1','ai-pipeline-code','Quy trình gồm xác định vấn đề, thu thập dữ liệu, huấn luyện, kiểm tra và đánh giá. Thiếu kiểm thử dễ khiến nhóm tin kết quả chưa được chứng minh. Ghi lại từng bước giúp nhóm khác lặp lại được thí nghiệm và kiểm tra kết luận.','Phiên bản A bỏ kiểm thử, phiên bản B thêm bước thử và lưu kết quả theo nhóm.','Lắp pipeline A thiếu kiểm thử|Chạy và đọc cảnh báo|Thêm bước thử để tạo phiên bản B','Pipeline học xong rồi dùng ngay đang thiếu gì?','Kiểm tra và đánh giá kết quả',['Đổi tên nhóm','Trang trí giao diện'],'Mô hình cần được kiểm tra trước khi dùng kết quả.'),
    lesson('5.D2.1 · 5.D2.MR1','grade-5-learning-leaves','Bổ sung, cập nhật dữ liệu có thể cải thiện hệ thống. Cần sửa đúng điểm yếu và kiểm chứng, không mặc định thêm mẫu sẽ luôn tốt. So sánh chỉ có nghĩa khi bộ thử được giữ nguyên giữa hai phiên bản.','Mô hình sai với lá trong bóng râm; bổ sung mẫu phù hợp rồi so sánh trên bộ thử giữ nguyên.','Ghi điểm yếu của mô hình A|Bổ sung mẫu liên quan và tạo B|So đúng sai và nêu thay đổi','Thêm dữ liệu xong có thể kết luận tốt hơn ngay không?','Không, cần kiểm thử và so sánh',['Có vì số mẫu tăng','Có nếu tệp lớn hơn'],'Dữ liệu thêm có thể không phù hợp hoặc sai nhãn; kết quả cần được đo.'),
    lesson('5.D1.1 · 5.D2.1','ai-pipeline-code','Giải pháp AI cần vấn đề rõ, dữ liệu phù hợp, tiêu chí đánh giá và người giám sát. Hồ sơ cần ghi cả giới hạn. Tiêu chí cần đo được, ví dụ số lần phân loại đúng trên một bộ thử cố định.','Nhóm thiết kế phân loại rác lớp học với tiêu chí đúng theo nhóm và cách xử lý vật lạ.','Viết vấn đề và người dùng|Lắp dữ liệu, học và kiểm thử|Nêu giới hạn cùng cách người giám sát can thiệp','Bản mô tả giải pháp nào đầy đủ hơn?','Có mục tiêu, dữ liệu, cách thử và người kiểm tra',['Chỉ có tên và logo','Chỉ có kết quả đẹp nhất'],'Giải pháp cần có cách kiểm chứng và vận hành có trách nhiệm.'),
    lesson('5.B1.1 · 5.B1.2','fair-data-lab','Công bằng cần xem tác động tới nhiều nhóm. Chia đều số mẫu không tự bảo đảm tỷ lệ đúng hay lợi ích bằng nhau. Vì thế cần đọc kết quả theo từng nhóm và xem ai chịu thiệt khi máy dự đoán sai.','Ba nhóm có cùng số mẫu học nhưng đúng 8/10, 6/10 và 7/10 trong kiểm thử.','Cân số mẫu ba nhóm|Đọc tỷ lệ đúng từng nhóm|Nêu nhóm cần xem thêm và lý do','Mẫu học bằng nhau nhưng kết quả khác nhau cho thấy gì?','Chưa đủ căn cứ kết luận công bằng',['Đã công bằng hoàn toàn','Nhóm sai nhiều tự có lỗi'],'Cần xem lỗi, bối cảnh và tác động, không chỉ đếm mẫu học.'),
    lesson('5.B2.1 · 5.B2.MR1','fair-data-lab','Giúp AI công bằng hơn cần dữ liệu đa dạng, tránh định kiến và kiểm tra kết quả theo nhóm. Không bỏ nhóm khó để làm đẹp điểm. Mỗi lần bổ sung dữ liệu đều cần hỏi ý kiến người liên quan và có người lớn hỗ trợ.','Mô hình kém với một giọng địa phương; nhóm tìm ví dụ phù hợp và xem lại cách đánh giá.','Tìm nhóm có ít ví dụ|Đề xuất nguyên tắc thu dữ liệu đa dạng|Kiểm tra lại kết quả và tác động','Cách nào giúp giảm thiếu sót với một nhóm người dùng?','Bổ sung phù hợp, kiểm tra riêng nhóm đó',['Loại nhóm đó khỏi báo cáo','Chỉ công bố điểm trung bình'],'Kiểm tra theo nhóm giúp không che khuất người bị ảnh hưởng.'),
    lesson('5.B3.1','grade-5-explain-ai','Hiểu căn cứ quyết định giúp đánh giá độ tin cậy. Giải thích cần gắn với đặc điểm, phép thử và giới hạn, không chỉ lời khẳng định máy thông minh. Một phép thử giữ nguyên vật và chỉ đổi bối cảnh giúp lộ ra căn cứ máy đang dựa vào.','Máy đoán lá bệnh vì nền vàng; giữ lá và đổi nền giúp kiểm tra căn cứ sai này.','Đặt giả thuyết máy dựa vào nền|Giữ lá, đổi nền và quan sát|Giải thích kết quả cùng điều chưa chắc','Giải thích nào có thể kiểm chứng được?','Giữ cùng lá, đổi nền để xem dự đoán có đổi không',['Máy đúng vì rất thông minh','Máy thích lá này'],'Phép thử cụ thể giúp kiểm tra điều gì ảnh hưởng tới quyết định.')
  ]
}

// Rotate answer position per lesson without changing answer/feedback association.
for (const [grade, lessons] of Object.entries(primaryLessonDetails)) lessons.forEach((item,index)=>{
  const shift=(Number(grade)+index)%item.quiz.options.length
  item.quiz.options=[...item.quiz.options.slice(shift),...item.quiz.options.slice(0,shift)]
  item.quiz.correct=(3-shift)%3
})

// Trạm thực hành phụ của một tiết. Mỗi lớp có 8 trò nhưng 12 tiết, nên nếu mỗi tiết chỉ trỏ
// tới đúng một trò thì vài trò không bao giờ mở được từ bài học. Chỉ ghép khi mã chuẩn của
// trò nằm trong mã chuẩn của tiết (riêng lớp 2 tiết 4 ghép theo chủ đề dữ liệu âm thanh).
export const primaryLessonExtraGames = {
  1: { 2: ['sensor-path'] },
  2: { 3: ['sound-lab-journey'], 6: ['pattern-lanterns'], 7: ['robot-command-debug'] },
  3: { 8: ['fact-check-code'] }
}
