import React from 'react'
import { countDecisionPoints, scoreForMistakes } from '../runtime/activityRuntime.js'
import { Bot, Check, RotateCcw, Sparkles, Star, Trophy, X } from 'lucide-react'
import { dataGardenEngine, gardenTestSample } from '../engines/dataGardenEngine.js'
import { useActivitySession } from '../runtime/useActivitySession.js'
import './PrimaryDataGardenLab.css'

const labelText=label=>label==='fruit'?'Trái cây':'Không phải trái cây'

export default function PrimaryDataGardenLab({game,best,close,onComplete}){
  const session=useActivitySession(game,dataGardenEngine,onComplete)
  const complete=session.state.status==='complete'
  const signatures=new Set(session.data.runs.map(run=>run.datasetSignature)).size
  return <div className="modal-backdrop game-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="game-modal rich-game-modal garden-lab-modal" role="dialog" aria-modal="true" aria-labelledby="garden-lab-title" style={{'--game-color':game.color}}><button id="close-game" className="close" onClick={close} aria-label="Đóng vườn dữ liệu"><X/></button>
    {!complete?<><header className="game-modal-head"><span className="game-hero-icon" aria-hidden="true">{game.icon}</span><div><small>VƯỜN DỮ LIỆU LỚP {game.grade} · {game.ministry}</small><h2 id="garden-lab-title">{game.title}</h2><p>{game.description}</p><span className="modal-ai-label"><Bot size={14}/> Mô phỏng gần mẫu nhất · dữ liệu chỉ lưu trên thiết bị</span></div></header>
      {!session.ready?<p className="lab-loading" role="status">Đang khôi phục hoạt động…</p>:<div className="garden-lab-body">
        <aside className="garden-criterion"><small>TIÊU CHÍ PHÂN LOẠI</small><b>Trong bài này, “trái cây” là bộ phận của cây có hạt ở bên trong.</b><p>Ví dụ: táo có hạt → trái cây; quả bóng không phải bộ phận của cây → không phải trái cây.</p></aside>
        <section className="garden-test" aria-labelledby="garden-test-title"><div><span aria-hidden="true">{gardenTestSample.icon}</span><div><small>MẪU CHƯA GẶP</small><h3 id="garden-test-title">{session.data.revealed?'Cà rốt mọc dưới đất và không có hạt bên trong.':'Một vật màu cam, thuôn dài.'}</h3></div></div>
          {!session.data.revealed?<><p>Thông tin này đã đủ để áp dụng tiêu chí chưa?</p><div className="garden-actions"><button id="garden-predict-fruit" onClick={()=>session.act({type:'predict',label:'fruit'})}>Trái cây</button><button id="garden-predict-other" onClick={()=>session.act({type:'predict',label:'other'})}>Không phải</button><button id="garden-predict-unknown" className={session.data.uncertaintyChecked?'selected':''} onClick={()=>session.act({type:'predict',label:'unknown'})}>Chưa đủ thông tin</button></div>{session.data.uncertaintyChecked&&<button id="garden-reveal" className="primary" onClick={()=>session.act({type:'reveal'})}>Xem thêm dấu hiệu</button>}</>:<><p>Dùng tiêu chí để dự đoán nhãn của mẫu mới.</p><div className="garden-actions"><button id="garden-label-fruit" onClick={()=>session.act({type:'predict',label:'fruit'})}>Trái cây</button><button id="garden-label-other" className={session.data.testLabel==='other'?'selected':''} onClick={()=>session.act({type:'predict',label:'other'})}>Không phải trái cây</button></div></>}
        </section>
        <section aria-labelledby="garden-data-title"><div className="leaf-section-heading"><div><small>BỘ VÍ DỤ CỦA NHÓM TRƯỚC</small><h3 id="garden-data-title">Kiểm tra từng nhãn theo tiêu chí</h3></div><span>{session.data.corrections.length} lần sửa</span></div><div className="garden-dataset">{session.data.dataset.map(item=><article key={item.id}><span aria-hidden="true">{item.icon}</span><div><b>{item.name}</b><small>{item.plantPart?'Bộ phận của cây':'Không phải bộ phận của cây'} · {item.seedsInside?'có hạt bên trong':'không có hạt bên trong'}</small></div><div><button id={`garden-${item.id}-fruit`} className={item.label==='fruit'?'active':''} disabled={!session.data.runs.length} onClick={()=>session.act({type:'label',id:item.id,label:'fruit'})}>Trái cây</button><button id={`garden-${item.id}-other`} className={item.label==='other'?'active':''} disabled={!session.data.runs.length} onClick={()=>session.act({type:'label',id:item.id,label:'other'})}>Không phải</button></div></article>)}</div>
          <button id="garden-run" className="primary garden-run" disabled={!session.data.testLabel} onClick={()=>session.act({type:'run'})}><Sparkles size={16}/> Chạy mô phỏng lần {session.data.runs.length+1}</button>
        </section>
        {session.data.runs.length>0&&<section aria-labelledby="garden-runs-title"><div className="leaf-section-heading"><div><small>SO SÁNH TRÊN CÙNG MẪU</small><h3 id="garden-runs-title">Kết quả các lần chạy</h3></div><span>{signatures} bộ nhãn</span></div><div className="garden-runs">{session.data.runs.map((run,index)=><article key={run.runId}><b>Lần {index+1}: dự đoán {labelText(run.result.label)}</b><p>Mẫu gần nhất: {run.dataset.find(item=>item.id===run.result.nearestId)?.name} · Nhãn chuẩn: {labelText(run.result.expected)}</p><small>{run.result.correct?'Dự đoán khớp nhãn kiểm chứng':'Dự đoán chưa khớp nhãn kiểm chứng'}</small></article>)}</div></section>}
        {signatures>=2&&<section className="garden-reason"><small>GIẢI THÍCH BẰNG CHỨNG</small><p>Vì sao kết quả lần hai thay đổi?</p><div className="garden-actions"><button id="garden-reason-color" className={session.data.reason==='color'?'selected':''} onClick={()=>session.act({type:'reason',value:'color'})}>Vì màu cam luôn là trái cây</button><button id="garden-reason-label" className={session.data.reason==='label-evidence'?'selected':''} onClick={()=>session.act({type:'reason',value:'label-evidence'})}>Vì sửa nhãn sai làm mẫu gần nhất có nhãn đúng hơn</button></div><button id="finish-garden-lab" className="primary" disabled={session.data.reason!=='label-evidence'} onClick={()=>session.act({type:'finish'})}>Hoàn thành <Check size={16}/></button></section>}
        <p className={signatures>=2?'game-message success':'game-message'} aria-live="polite">{dataGardenEngine.getFeedback(session.data)}</p>{session.storageError&&<p className="game-message" role="alert">{session.storageError}</p>}
      </div>}<footer className="game-modal-footer"><span>{best?`Kỷ lục: ${best}/3 sao`:'Màu sắc một mình chưa đủ để phân loại theo tiêu chí.'}</span><div className="live-stars"><Star size={17} fill="currentColor"/> {scoreForMistakes(session.data.mistakes, countDecisionPoints(game))}/3 sao</div></footer></>:<div className="game-complete"><span className="reward-cup"><Trophy/></span><small>HOÀN THÀNH VƯỜN DỮ LIỆU</small><h2 id="garden-lab-title">Em đã sửa dữ liệu bằng bằng chứng!</h2><p>Dự đoán mẫu mới, hai bộ nhãn và kết quả trước/sau đã được lưu.</p><div className="reward-stars" aria-label={`${session.state.score} sao`}>{[1,2,3].map(value=><Star key={value} fill={value<=session.state.score?'currentColor':'none'}/>)}</div><div className="complete-actions"><button id="game-replay" className="secondary" onClick={session.restart}><RotateCcw size={17}/> Làm lại</button><button id="game-finish" className="primary" onClick={close}>Nhận sao <Check size={17}/></button></div></div>}
  </section></div>
}
