import React from 'react'
import { Bot, Check, RotateCcw, Star, Trophy, X } from 'lucide-react'
import { evidenceCases, evidenceDetectiveEngine } from '../engines/evidenceDetectiveEngine.js'
import { useActivitySession } from '../runtime/useActivitySession.js'
import './PrimaryEvidenceDetective.css'

const verdicts=[['supported','Được đoạn trích ủng hộ'],['refuted','Bị đoạn trích bác bỏ'],['insufficient','Chưa đủ bằng chứng']]

export default function PrimaryEvidenceDetective({game,best,close,onComplete}){
  const session=useActivitySession(game,evidenceDetectiveEngine,onComplete)
  const complete=session.state.status==='complete'
  const item=evidenceCases[Math.min(session.data.caseIndex,evidenceCases.length-1)]
  return <div className="modal-backdrop game-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="game-modal rich-game-modal evidence-modal" role="dialog" aria-modal="true" aria-labelledby="evidence-title" style={{'--game-color':game.color}}><button id="close-game" className="close" onClick={close} aria-label="Đóng thám tử bằng chứng"><X/></button>
    {!complete?<><header className="game-modal-head"><span className="game-hero-icon" aria-hidden="true">{game.icon}</span><div><small>THÁM TỬ BẰNG CHỨNG LỚP {game.grade}</small><h2 id="evidence-title">{game.title}</h2><p>{game.description}</p><span className="modal-ai-label"><Bot size={14}/> Đọc nội dung trước khi tin câu trả lời AI</span></div></header>
      {!session.ready?<p className="lab-loading" role="status">Đang khôi phục hoạt động…</p>:<div className="evidence-body"><div className="evidence-progress" aria-label={`${session.data.answers.length} trên ${evidenceCases.length} phát biểu đã kiểm tra`}>{evidenceCases.map((value,index)=><span key={value.id} className={index<session.data.answers.length?'done':index===session.data.caseIndex?'current':''}>{index<session.data.answers.length?<Check/>:index+1}</span>)}</div>
        <section className="claim-card"><small>PHÁT BIỂU CẦN KIỂM TRA</small><h3>“{item.claim}”</h3><p>Tên nguồn có thể giống nhau. Em cần đọc đoạn trích liên quan trực tiếp.</p></section>
        <section aria-labelledby="source-title"><div className="leaf-section-heading"><div><small>BƯỚC 1</small><h3 id="source-title">Chọn đoạn bằng chứng</h3></div></div><div className="source-cards">{item.sources.map(source=><button id={`evidence-source-${source.id}`} key={source.id} className={session.data.selectedSource===source.id?'selected':''} aria-pressed={session.data.selectedSource===source.id} onClick={()=>session.act({type:'source',id:source.id})}><b>{source.title}</b><span>“{source.excerpt}”</span></button>)}</div></section>
        <section aria-labelledby="verdict-title"><div className="leaf-section-heading"><div><small>BƯỚC 2</small><h3 id="verdict-title">Đoạn em chọn cho biết điều gì?</h3></div></div><div className="verdict-actions">{verdicts.map(([value,label])=><button id={`evidence-verdict-${value}`} key={value} className={session.data.selectedVerdict===value?'selected':''} aria-pressed={session.data.selectedVerdict===value} onClick={()=>session.act({type:'verdict',value})}>{label}</button>)}</div></section>
        <button id="evidence-submit" className="primary evidence-submit" disabled={!session.data.selectedSource||!session.data.selectedVerdict} onClick={()=>session.act({type:'submit'})}>Kiểm tra lựa chọn <Check size={16}/></button><p className={session.data.message.startsWith('Đúng')?'game-message success':'game-message'} aria-live="polite">{evidenceDetectiveEngine.getFeedback(session.data)}</p>{session.storageError&&<p className="game-message" role="alert">{session.storageError}</p>}
      </div>}<footer className="game-modal-footer"><span>{best?`Kỷ lục: ${best}/3 sao`:'Nguồn quen thuộc vẫn có thể chứa đoạn không liên quan.'}</span><div className="live-stars"><Star size={17} fill="currentColor"/> {Math.max(1,3-Math.min(2,session.data.mistakes))}/3 sao</div></footer></>:<div className="game-complete"><span className="reward-cup"><Trophy/></span><small>HOÀN THÀNH KIỂM CHỨNG</small><h2 id="evidence-title">Em đã đọc bằng chứng trước khi kết luận!</h2><p>Sáu phát biểu, đoạn nguồn và kết luận đã được lưu cho giáo viên.</p><div className="reward-stars" aria-label={`${session.state.score} sao`}>{[1,2,3].map(value=><Star key={value} fill={value<=session.state.score?'currentColor':'none'}/>)}</div><div className="complete-actions"><button id="game-replay" className="secondary" onClick={session.restart}><RotateCcw size={17}/> Làm lại</button><button id="game-finish" className="primary" onClick={close}>Nhận sao <Check size={17}/></button></div></div>}
  </section></div>
}
