import React from 'react'
import { scoreForMistakes } from '../runtime/activityRuntime.js'
import { Bot, Check, ChevronDown, ChevronUp, RotateCcw, Sparkles, Star, Trash2, Trophy, X } from 'lucide-react'
import { primaryPipelineEngine, primaryPipelineStages } from '../engines/primaryPipelineEngine.js'
import { useActivitySession } from '../runtime/useActivitySession.js'
import './PrimaryPipelineLab.css'

export default function PrimaryPipelineLab({game,best,close,onComplete}){
  const session=useActivitySession(game,primaryPipelineEngine,onComplete)
  const complete=session.state.status==='complete'
  const stage=id=>primaryPipelineStages.find(item=>item.id===id)
  const pipelineVersions=new Set(session.data.runs.map(run=>run.pipelineSignature)).size
  const datasetVersions=new Set(session.data.runs.map(run=>run.datasetSignature)).size
  return <div className="modal-backdrop game-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="game-modal rich-game-modal primary-pipeline-modal" role="dialog" aria-modal="true" aria-labelledby="primary-pipeline-title" style={{'--game-color':game.color}}><button id="close-game" className="close" onClick={close} aria-label="Đóng phòng lab pipeline"><X/></button>
    {!complete?<><header className="game-modal-head"><span className="game-hero-icon" aria-hidden="true">{game.icon}</span><div><small>PIPELINE A/B LỚP {game.grade}</small><h2 id="primary-pipeline-title">{game.title}</h2><p>{game.description}</p><span className="modal-ai-label"><Bot size={14}/> Mô phỏng pipeline và kết quả theo nhóm · lưu trên thiết bị</span></div></header>
      {!session.ready?<p className="lab-loading" role="status">Đang khôi phục hoạt động…</p>:<div className="primary-pipeline-body"><section aria-labelledby="primary-pipeline-editor"><div className="leaf-section-heading"><div><small>CẤU TRÚC PIPELINE</small><h3 id="primary-pipeline-editor">Lắp, kiểm tra và sửa từng bước</h3></div><span>{session.data.pipeline.length}/5 bước</span></div><div className="primary-pipeline-layout"><div className="primary-stage-palette">{primaryPipelineStages.map(item=><button id={`primary-stage-${item.id}`} key={item.id} disabled={session.data.pipeline.includes(item.id)} onClick={()=>session.act({type:'add',id:item.id})}>{item.label}</button>)}</div><div className="primary-stage-program">{session.data.pipeline.length?session.data.pipeline.map((id,index)=><article key={id}><span>{index+1}</span><b>{stage(id)?.label}</b><div><button id={`primary-stage-up-${id}`} aria-label={`Đưa ${stage(id)?.label} lên`} disabled={!index} onClick={()=>session.act({type:'move',id,offset:-1})}><ChevronUp/></button><button id={`primary-stage-down-${id}`} aria-label={`Đưa ${stage(id)?.label} xuống`} disabled={index===session.data.pipeline.length-1} onClick={()=>session.act({type:'move',id,offset:1})}><ChevronDown/></button><button id={`primary-stage-remove-${id}`} aria-label={`Bỏ ${stage(id)?.label}`} onClick={()=>session.act({type:'remove',id})}><Trash2/></button></div></article>):<p>Chọn các bước để tạo phiên bản A.</p>}</div></div></section>
        <section aria-labelledby="primary-data-groups"><div className="leaf-section-heading"><div><small>DỮ LIỆU MINH HỌA</small><h3 id="primary-data-groups">Số mẫu học theo nhóm</h3></div><span>{session.data.counts.reduce((sum,value)=>sum+value,0)} mẫu</span></div><div className="primary-group-data">{session.data.counts.map((count,index)=><article key={index}><b>Nhóm {['A','B','C'][index]}</b><strong>{count}</strong><div><button id={`primary-data-remove-${index}`} disabled={!session.data.runs.length||!count} onClick={()=>session.act({type:'sample',group:index,delta:-1})}>−</button><button id={`primary-data-add-${index}`} disabled={!session.data.runs.length||count>=4} onClick={()=>session.act({type:'sample',group:index,delta:1})}>+</button></div></article>)}</div><small className="primary-data-note">Sau lần chạy A, em có thể bổ sung nhóm còn thiếu cho phiên bản B.</small></section>
        <button id="primary-pipeline-run" className="primary primary-pipeline-run" disabled={!['problem','data','train'].every(id=>session.data.pipeline.includes(id))} onClick={()=>session.act({type:'run'})}><Sparkles size={16}/> Chạy phiên bản {session.data.runs.length?'B':'A'}</button>
        {session.data.runs.length>0&&<section aria-labelledby="primary-run-history"><div className="leaf-section-heading"><div><small>KẾT QUẢ A/B</small><h3 id="primary-run-history">So sánh hai phiên bản</h3></div><span>{pipelineVersions} pipeline · {datasetVersions} bộ dữ liệu</span></div><div className="primary-run-grid">{session.data.runs.map((run,index)=><article key={run.runId}><header><b>Phiên bản {index?'B':'A'}</b><span>{run.pipeline.length} bước · dữ liệu {run.counts.join('–')}</span></header><p>{run.result.message}</p><div>{run.result.groupResults.map(group=><span key={group.group}><b>Nhóm {group.group}</b>{group.tested?`${group.correct}/${group.total} đúng`:'Chưa kiểm thử'}</span>)}</div></article>)}</div></section>}
        {session.data.runs.length>=2&&<section className="primary-pipeline-reflection"><label htmlFor="primary-pipeline-reflection">Em đã sửa gì và kết quả B cho thấy điều gì?</label><textarea id="primary-pipeline-reflection" maxLength="180" value={session.data.reflection} onChange={event=>session.act({type:'reflection',value:event.target.value})} placeholder="Ví dụ: Em thêm bước kiểm thử và mẫu nhóm C…"/><div><span>{session.data.reflection.trim().length}/15 ký tự tối thiểu</span><button id="finish-primary-pipeline" className="primary" disabled={session.data.reflection.trim().length<15||pipelineVersions<2||datasetVersions<2||!session.data.runs.at(-1)?.result.complete||session.data.runs.at(-1)?.result.covered<3} onClick={()=>session.act({type:'finish'})}>Hoàn thành <Check size={16}/></button></div></section>}
        <p className={session.data.runs.at(-1)?.result.complete&&session.data.runs.at(-1)?.result.covered===3?'game-message success':'game-message'} aria-live="polite">{primaryPipelineEngine.getFeedback(session.data)}</p>{session.storageError&&<p className="game-message" role="alert">{session.storageError}</p>}
      </div>}<footer className="game-modal-footer"><span>{best?`Kỷ lục: ${best}/3 sao`:'Kết quả là dữ liệu minh họa cố định, không phải dự đoán của mô hình thật.'}</span><div className="live-stars"><Star size={17} fill="currentColor"/> {scoreForMistakes(session.data.mistakes)}/3 sao</div></footer></>:<div className="game-complete"><span className="reward-cup"><Trophy/></span><small>HOÀN THÀNH PIPELINE A/B</small><h2 id="primary-pipeline-title">Em đã cải tiến bằng kết quả kiểm thử!</h2><p>Hai pipeline, bộ dữ liệu, kết quả và lời giải thích đã được lưu.</p><div className="reward-stars" aria-label={`${session.state.score} sao`}>{[1,2,3].map(value=><Star key={value} fill={value<=session.state.score?'currentColor':'none'}/>)}</div><div className="complete-actions"><button id="game-replay" className="secondary" onClick={session.restart}><RotateCcw size={17}/> Làm lại</button><button id="game-finish" className="primary" onClick={close}>Nhận sao <Check size={17}/></button></div></div>}
  </section></div>
}
